surrealdb/docs.surrealdb.com

docs/integration/websocket.mdx
=> Docs: Update websocket let response and request

docs/integration/websocket.mdx
=> Docs: update signin and  signup syntax for websocket 

docs/installation/upgrading/beta8-to-beta9.mdx
v1.0.0-beta.8 to v1.0.0-beta.9
=> Docs: Add migration guide for upgrading from

src/css/custom.scss
It fixes the menu width on the iPad portrait mode
Closes #99
=> feat(ipad-fixes): Menu width on ipad portrait mode

docs/surrealql/statements/use.mdx, versioned_docs/version-nightly/surrealql/statements/use.mdx
The intro text was copied from update statement, fixing that here, so the text is the same as old use statement text
=> fix use satement page

docs/surrealql/functions/array.mdx, versioned_docs/version-nightly/surrealql/functions/array.mdx
Fixing typo raised in issue #126
=> fix typo for array distinct

docs/integration/sdks/javascript.mdx
=> fix table spelling in example 

docs/surrealql/demo.mdx
Expanding the text into a step by step example.
=> Adding a clear cli example

src/theme/SearchBar/index.tsx, src/theme/SearchBar/styles.module.css
=> Handle CTRL+K search hotkey

docs/surrealql/datamodel/geometries.mdx, docs/surrealql/statements/define/analyzer.mdx, versioned_docs/version-1.1.0/surrealql/statements/define/analyzer.mdx, versioned_docs/version-nightly/surrealql/statements/define/analyzer.mdx
Which got me thinking, I don't actually see examples how to use the analyzers? 
Like, what's the syntax and where do I define their application after creating them?
Update: Ah, I see their later application in creating indexes.
=> Doc: Fix example for blank analyzer

docs/surrealql/functions/array.mdx, versioned_docs/version-1.1.0/surrealql/functions/array.mdx, versioned_docs/version-nightly/surrealql/functions/array.mdx
- fixed a few typos
- added description and examples for `array::max` and`array::min`
- fixed example descriptions for `array::prepend`, `array::sort` and `array::reverse`
=> Fix docs for array functions

src/theme/EditThisPage/index.js
It add the Edit this Page component and it renames to Edit this page on GitHub.
=> feat(edit-this-page): Adds Edit This Page component

src/theme/SearchBar/styles.module.css
=> Improve styles on search hotkey indicator

versioned_docs/version-1.0.x/surrealql/operators.mdx, versioned_docs/version-1.1.x/surrealql/operators.mdx, versioned_docs/version-nightly/surrealql/operators.mdx
Should fix the docs for modulo operator (and some minor related quick fixes)
=> Fix docs for modulo operator

versioned_docs/version-1.0.x/surrealql/statements/live-select.mdx, versioned_docs/version-1.1.x/surrealql/statements/kill.mdx, versioned_docs/version-1.1.x/surrealql/statements/live-select.mdx, versioned_docs/version-nightly/surrealql/statements/live-select.mdx
People are confused about interface use cases etc. We want to flesh out the docs to avoid further confusion.
- Improve understanding of UUID
- Improve understanding of protocol
- Improve understanding of access (FETCH)
- Examples of diff
- Consistency guarantees
=> Improve Live Query documentation

versioned_docs/version-1.0.x/surrealql/statements/create.mdx, versioned_docs/version-1.0.x/surrealql/statements/insert.mdx, versioned_docs/version-1.0.x/surrealql/statements/update.mdx, versioned_docs/version-1.1.x/surrealql/statements/create.mdx, versioned_docs/version-1.1.x/surrealql/statements/insert.mdx, versioned_docs/version-1.1.x/surrealql/statements/update.mdx, versioned_docs/version-nightly/surrealql/statements/create.mdx, versioned_docs/version-nightly/surrealql/statements/insert.mdx, versioned_docs/version-nightly/surrealql/statements/update.mdx
=> Add warning to  CREATE, INSERT, and UPDATE statements for graph relationships

versioned_docs/version-1.1.x/deployment/google.mdx
=> fix parsing SURREALDB_URL with jq

versioned_docs/version-1.0.x/integration/sdks/rust.mdx, versioned_docs/version-1.1.x/integration/sdks/rust.mdx, versioned_docs/version-nightly/integration/sdks/rust.mdx
Removing extra line for "Then make sure your SurrealDB server..."
=> Removing duplicate line in rust.mdx

versioned_docs/version-1.1.x/introduction/sql.mdx
Corrected inner join syntax error at "SQL"
=> fix SQL syntax error sql.mdx

versioned_docs/version-1.0.x/surrealql/functions/string.mdx, versioned_docs/version-1.1.x/surrealql/functions/string.mdx, versioned_docs/version-nightly/surrealql/functions/string.mdx
=> Update string::slice function documentation

versioned_docs/version-1.0.x/installation/running/docker.mdx, versioned_docs/version-1.1.x/installation/running/docker.mdx, versioned_docs/version-nightly/installation/running/docker.mdx
=> Update running docker with authentication instructions

versioned_docs/version-1.0.x/surrealql/statements/define/analyzer.mdx, versioned_docs/version-1.1.x/surrealql/statements/define/analyzer.mdx, versioned_docs/version-nightly/surrealql/statements/define/analyzer.mdx
- Update the docs with details about ngram filter
- Remove example outputs from the syntax queries
- Fixes #233
=> Update the docs with details about ngram filter. 

versioned_docs/version-1.0.x/surrealql/datamodel/ids.mdx, versioned_docs/version-1.1.x/surrealql/datamodel/ids.mdx, versioned_docs/version-nightly/surrealql/datamodel/ids.mdx
=> docs-273-fix-typo

versioned_docs/version-1.0.x/integration/http.mdx, versioned_docs/version-1.1.x/integration/http.mdx, versioned_docs/version-nightly/integration/http.mdx
=> Docs: Update HTTP endpoint documentation to show using postman

versioned_docs/version-1.0.x/installation/overview.mdx, versioned_docs/version-1.0.x/introduction/start.mdx, versioned_docs/version-1.1.x/installation/overview.mdx, versioned_docs/version-1.1.x/introduction/start.mdx, versioned_docs/version-nightly/installation/overview.mdx, versioned_docs/version-nightly/introduction/start.mdx
Direct devs to install the binary from https://surrealdb.com/install before getting started.
=> Update start.mdx to include link to the Installation page

versioned_docs/version-nightly/cli/upgrade.mdx, versioned_docs/version-nightly/surrealql/statements/define/field.mdx
Updates the nightly docs in preparation of the 1.2.0 beta release
=> Sync nightly

versioned_docs/version-1.0.x/surrealql/statements/show.mdx, versioned_docs/version-1.1.x/surrealql/statements/show.mdx, versioned_docs/version-1.2.x/surrealql/statements/show.mdx, versioned_docs/version-nightly/surrealql/statements/show.mdx
Improved the example and added links to change feeds product page.
=> Improving show statement

src/css/custom.scss
It adds a 2px border instead of 1px on the main feedback button.
=> feat(feedback-button-border): Adds a 2px border

versioned_docs/version-1.2.x/surrealql/datamodel/geometries.mdx, versioned_docs/version-nightly/surrealql/datamodel/geometries.mdx
=> Docs: Update geometries in datamodel

versioned_docs/version-1.0.x/surrealql/statements/define/analyzer.mdx, versioned_docs/version-1.1.x/surrealql/statements/define/analyzer.mdx, versioned_docs/version-1.2.x/surrealql/statements/define/analyzer.mdx, versioned_docs/version-nightly/surrealql/statements/define/analyzer.mdx
=> Update define index examples

versioned_docs/version-1.0.x/surrealql/statements/remove.mdx, versioned_docs/version-1.1.x/surrealql/statements/remove.mdx, versioned_docs/version-1.2.x/surrealql/statements/remove.mdx, versioned_docs/version-nightly/surrealql/statements/remove.mdx
#318 
- add REMOVE ANALYZER
- add REMOVE USER writer ON DATABASE;
- group statements
- sort by alphabet in groups
=> add REMOVE ANALYZER to REMOVE examples and schema

versioned_docs/version-1.0.x/surrealql/datamodel/casting.mdx, versioned_docs/version-1.0.x/surrealql/functions/array.mdx, versioned_docs/version-1.0.x/surrealql/functions/math.mdx, versioned_docs/version-1.0.x/surrealql/functions/type.mdx, versioned_docs/version-1.0.x/surrealql/operators.mdx, versioned_docs/version-1.1.x/surrealql/datamodel/casting.mdx, versioned_docs/version-1.1.x/surrealql/functions/array.mdx, versioned_docs/version-1.1.x/surrealql/functions/math.mdx, versioned_docs/version-1.1.x/surrealql/functions/type.mdx, versioned_docs/version-1.1.x/surrealql/operators.mdx, versioned_docs/version-1.2.x/surrealql/datamodel/casting.mdx, versioned_docs/version-1.2.x/surrealql/functions/array.mdx, versioned_docs/version-1.2.x/surrealql/functions/math.mdx, versioned_docs/version-1.2.x/surrealql/functions/type.mdx, versioned_docs/version-1.2.x/surrealql/operators.mdx, versioned_docs/version-nightly/surrealql/datamodel/casting.mdx, versioned_docs/version-nightly/surrealql/functions/array.mdx, versioned_docs/version-nightly/surrealql/functions/math.mdx, versioned_docs/version-nightly/surrealql/functions/type.mdx, versioned_docs/version-nightly/surrealql/operators.mdx
=> Docs: Update datetime and array functions

versioned_docs/version-1.0.x/faqs/overview.mdx, versioned_docs/version-1.1.x/faqs/overview.mdx, versioned_docs/version-1.2.x/faqs/overview.mdx, versioned_docs/version-nightly/faqs/overview.mdx
=> Docs: Update FAQ for indexes

versioned_docs/version-1.0.x/surrealql/statements/begin.mdx, versioned_docs/version-1.1.x/surrealql/statements/begin.mdx, versioned_docs/version-1.2.x/surrealql/statements/begin.mdx, versioned_docs/version-nightly/surrealql/statements/begin.mdx
=> Docs: Remove none valid SQL syntax

versioned_docs/version-1.0.x/installation/upgrading/beta8-to-beta9.mdx, versioned_docs/version-1.1.x/faqs/overview.mdx, versioned_docs/version-1.2.x/faqs/overview.mdx, versioned_docs/version-1.2.x/reference-guide/overview.mdx, versioned_docs/version-nightly/faqs/overview.mdx, versioned_docs/version-nightly/reference-guide/full-text-search.mdx
=> Update links 

versioned_docs/version-1.1.x/surrealql/operators.mdx, versioned_docs/version-1.2.x/surrealql/operators.mdx, versioned_docs/version-nightly/surrealql/operators.mdx
Changed add operators documentation to describe its operation accurately.
Fixed #358
=> Correct documentation since 1.1.x for add operator

src/theme/Feedback/index.tsx
It increases the feddback textbox from 50 to 280 chars and it lets users know about it in the placeholder.
=> feat(increase-textbox-chars)

versioned_docs/version-1.0.x/integration/sdks/rust.mdx, versioned_docs/version-1.1.x/integration/sdks/rust.mdx, versioned_docs/version-1.2.x/integration/sdks/rust.mdx, versioned_docs/version-nightly/integration/sdks/rust.mdx
Adds example to retrieve unique id of a record
closes #244
=> Docs: Update Rust SDK code examples

versioned_docs/version-1.1.x/surrealql/datamodel/futures.mdx, versioned_docs/version-1.2.x/surrealql/datamodel/futures.mdx, versioned_docs/version-nightly/surrealql/datamodel/futures.mdx
Example was missing a type so the addition was throwing an error.
=> Docs: Update Futures type example

versioned_docs/version-1.0.x/introduction/start.mdx, versioned_docs/version-1.1.x/introduction/start.mdx, versioned_docs/version-1.2.x/introduction/start.mdx, versioned_docs/version-nightly/introduction/start.mdx
=> Docs: Change update and delete statement section

versioned_docs/version-nightly/surrealql/statements/define/analyzer.mdx, versioned_docs/version-nightly/surrealql/statements/define/database.mdx, versioned_docs/version-nightly/surrealql/statements/define/event.mdx, versioned_docs/version-nightly/surrealql/statements/define/field.mdx, versioned_docs/version-nightly/surrealql/statements/define/function.mdx, versioned_docs/version-nightly/surrealql/statements/define/indexes.mdx, versioned_docs/version-nightly/surrealql/statements/define/namespace.mdx, versioned_docs/version-nightly/surrealql/statements/define/overview.mdx, versioned_docs/version-nightly/surrealql/statements/define/param.mdx, versioned_docs/version-nightly/surrealql/statements/define/scope.mdx, versioned_docs/version-nightly/surrealql/statements/define/table.mdx, versioned_docs/version-nightly/surrealql/statements/define/token.mdx, versioned_docs/version-nightly/surrealql/statements/define/user.mdx, versioned_docs/version-nightly/surrealql/statements/remove.mdx
=> Docs: Add `IF (NOT) EXISTS` clause to define statements section

versioned_docs/version-1.2.x/introduction/mongo.mdx, versioned_docs/version-1.2.x/introduction/neo4j.mdx, versioned_docs/version-1.2.x/introduction/sql.mdx
It replaces the old tables with the new ones in some parts.
=> Feat(old-tables-conversion): Adds old tables style conversion

src/css/custom.scss, versioned_docs/version-1.x/introduction/start.mdx
This PR gives the learner option of using surrealist or CLI for the getting started guide and fixes the margin between code block and the next element
=> Add tab component in getting started guide

versioned_docs/version-1.x/surrealql/operators.mdx, versioned_docs/version-1.x/surrealql/statements/define/indexes.mdx
Added docs for M-tree type of index under DEFINE INDEX.
=> mtree index docs added

doc-surrealdb_versioned_docs/version-1.x/introduction/sql.mdx, doc-surrealdb_versioned_docs/version-1.x/security/capabilities.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/datamodel/datetimes.mdx
Some fixes for the old style tables.
=> feat(tables-leftovers-latest): Fixes old tables styles

doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/encoding.mdx
=> Docs: Add encoding functions for base64

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/break.mdx
=> Update break example

doc-surrealdb_versioned_docs/version-1.x/integration/index.mdx
=> Update index.mdx with Discord link

doc-surrealdb_versioned_docs/version-1.x/surrealql/datamodel/records.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/index.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/select.mdx, src/css/custom.scss
This PR adds https://youtu.be/TyX45cyZ-W0?si=FVFkXwPn7M9wX16P to the relevant sections in documentation.
=> Docs: Add explanatory videos and resources

doc-surrealdb_versioned_docs/version-1.x/surrealql/demo.mdx
- added sample queries to demo data
- updated links to use v2 dataset
=> Update demo data docs with example and v2 dataset

doc-surrealdb_versioned_docs/version-1.x/integration/rpc.mdx
=> Docs: Add tags for websocket only methods

doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/search.mdx
Related to: https://github.com/surrealdb/surrealdb/pull/3719
=> Explain optional boolean parameter search::highlight, search::offsets

src/theme/SearchBar/index.tsx, src/theme/SearchBar/styles.module.css
* Remove dead code
* Improve accessiblity using proper `ol` + `li` semantic HTML
* Update CSS style accordingly
No noticable UI change for a screenshot.
=> Improve accessiblity of search bar results

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/break.mdx
=> Docs: Fix conditional logic in break.mdx file

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/token.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/user.mdx
=> Docs: Update example for token and user IF NOT EXISTS

doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/rand.mdx
Change returned type in `rand:enum` function
=> Docs: Update rand.mdx

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/select.mdx
I've searched in the documentation on how to filter a subquery (e.g. sql-like HAVING) but didn't found anything.
But I've found [an example in the github issues](https://github.com/surrealdb/surrealdb/issues/2099#issuecomment-1595457866) which was helpful and should be mentioned in the docs.
=> feat: example for filtering a select subquery

doc-surrealdb_versioned_docs/version-1.x/cli/import.mdx
=> Docs: Update import command with note about import size limit

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/update.mdx
Interesting behaviour I noticed that should be documented.
=> Example showing UPDATE works with a record ID anywhere

doc-surrealdb_versioned_docs/version-1.x/surrealql/parameters.mdx
Will probably set this for review once about ten tips are found.
Edit: Going to set this single tip to review now so it can be merged, and going forward will collect tips on my machine and then only them into a PR once in a while that can be merged right away.
=> Add tip from Discord about getting the current item in an iterative operation

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/indexes.mdx
=> Docs: Add runnable examples and update Brute force section.

doc-surrealdb_versioned_docs/version-1.x/surrealql/operators.mdx
Modulo operator was added to the operator docs
=> Add missing % operator to operators.mdx

doc-surrealdb_versioned_docs/version-1.x/surrealql/datamodel/records.mdx
Fairly quick PR for a user who mentioned the following recently:
```
While trying to make schemad tables It is hard to find how types are supposed to be typed. array<TableName>, [TableName], array<object> all give errors.
```
=> Show how to define a record link in schema

doc-surrealdb_versioned_docs/version-1.x/surrealql/datamodel/arrays.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/datamodel/ids.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/datamodel/objects.mdx
@tobiemh added some nice examples yesterday at https://github.com/surrealdb/surrealdb/issues/3928#issuecomment-2108655314 and suggested they be put into the documentation. I expanded them a bit and added a few more examples on top.
=> More on object/array sorting

doc-surrealdb_versioned_docs/version-2.x/cli/start.mdx
Updates documentation to match https://github.com/surrealdb/surrealdb/pull/4054.
=> Update default value for `--bind` flag in 2.0

doc-surrealdb_versioned_docs/version-2.x/cli/start.mdx, doc-surrealdb_versioned_docs/version-2.x/installation/running/docker.mdx, doc-surrealdb_versioned_docs/version-2.x/installation/running/memory.mdx, doc-surrealdb_versioned_docs/version-2.x/introduction/start.mdx, doc-surrealdb_versioned_docs/version-2.x/tutorials/connect-to-surrealdb-via-ngrok-tunnel.mdx, doc-surrealdb_versioned_docs/version-2.x/tutorials/integrate-auth0-as-authentication-provider.mdx, doc-surrealdb_versioned_docs/version-2.x/tutorials/integrate-aws-cognito-as-authentication-provider.mdx, doc-surrealdb_versioned_docs/version-2.x/tutorials/working-with-surrealdb-over-http-via-postman.mdx
Updates documentation to match https://github.com/surrealdb/surrealdb/pull/4059.
=> Replace deprecated `--auth` flag in 2.0

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/live.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/live.mdx
RE https://github.com/surrealdb/surrealdb/issues/4026 add a doc note about params
Note this change is on the v2 code branch/directory, so not visible in preview
=> Add update to docs about params in live queries

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/indexes.mdx
=> Fix grammar in indexes.mdx

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/relate.mdx
https://github.com/surrealdb/surrealdb/issues/4093
=> Doc: Update RELATE statement documentation with note about creating records before using it

doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/database/string.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/functions/database/string.mdx
=> Add IP functions

doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/database/math.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/functions/database/math.mdx
Documents new math functions in `2.x`
https://github.com/surrealdb/surrealdb/pull/4132
Documents math constants in `1.x` and `2.x`
=> Implements new math functions

doc-surrealist_versioned_docs/version-2.x/index.mdx
While giving Surrealist a much closer look I've come to think that Explorer can be another starting point for a new user. The two types in very broad strokes:
* Query view: A developer that wants to start banging around to see what happens
* Explorer view: Someone – possibly not so techy – that wants to click on a few things to see what happens
=> Surrealist: Recommend two starting points

doc-surrealdb_versioned_docs/version-1.x/cli/upgrade.mdx, doc-surrealdb_versioned_docs/version-2.x/cli/upgrade.mdx
for installing the latest alpha version of SurrealDB
Closes #597
=> Doc: Add --alpha flag to upgrade command 

doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/update.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/upsert.mdx
Add more examples for `UPSERT`
=> Doc: Add examples for `UPSERT` and `UPDATE`

doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/define/function.mdx
=> Docs: Add permissions section to  `DEFINE FUNCTION` documentation

doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/remove.mdx
Changed Typo "ACCCESS" to "ACCESS"
=> Update remove.mdx to remove typo "ACCCESS"

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/indexes.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/define/indexes.mdx
Update the full-text search index documentation with details about the `SEARCH` keyword.
=> Update the full-text search index with keyword info

doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/define/access/record.mdx
Addresses https://github.com/surrealdb/surrealdb/issues/4229.
=> Specify required claim for record access with JWT

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/insert.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/insert.mdx
Minor edit to remove the underscores around "Note:"
=> Update insert.mdx to fix note

doc-surrealdb_versioned_docs/version-2.x/installation/running/docker.mdx
Update documentation considering https://github.com/surrealdb/surrealdb/pull/4276.
=> Document change in bind behavior for Docker

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/insert.mdx
This pull request gives an example to import data from an http endpoint by making a get request.
=> Added Bulk Insert Example Using HTTP functions

doc-surrealdb_versioned_docs/version-1.x/deployment/kubernetes.mdx, doc-surrealdb_versioned_docs/version-2.x/deployment/kubernetes.mdx
=> Chore: Update SurrealDB Helm chart with latest image tag

doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/define/access/record.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/return.mdx
https://github.com/surrealdb/surrealdb/pull/4298
=> Update 2.x `RETURN`-statement docs

doc-surrealdb_versioned_docs/version-1.x/reference-guide/full-text-search.mdx, doc-surrealdb_versioned_docs/version-2.x/reference-guide/full-text-search.mdx
Update the Full-Text search reference guide to make it more concise.
=> Update the Full-Text search reference guide to make it more concise.

doc-surrealdb_versioned_docs/version-1.x/tutorials/index.mdx, doc-surrealdb_versioned_docs/version-1.x/tutorials/using-github-actions.mdx, doc-surrealdb_versioned_docs/version-2.x/tutorials/index.mdx, doc-surrealdb_versioned_docs/version-2.x/tutorials/using-github-actions.mdx
A step-by-step guide of how to properly use the SurrealDB Github Action.
=> DEV-225(gh-actions-tutorial): Using GH Actions tutorial

doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/define/access/index.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/define/access/jwt.mdx
Document https://github.com/surrealdb/surrealdb/pull/4348.
=> Document `DEFINE ACCESS ... ON ROOT`

src/components/JS-SDK/list.mdx
It adds the WebAssembly linkage.
=> feat(wasm-links): Adds the WebAssembly linkage

docusaurus.config.js
Reverts surrealdb/docs.surrealdb.com#683
=> Revert "Remove trailing slashes from URLs"

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/table.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/define/table.mdx
Update examples for pre-comptued views
=> Update examples for pre-comptued views

doc-sdk-dotnet_versioned_docs/version-1.x/index.mdx, doc-sdk-golang_versioned_docs/version-1.x/index.mdx, doc-sdk-java_versioned_docs/version-1.x/index.mdx, doc-sdk-python_versioned_docs/version-1.x/index.mdx, doc-sdk-rust_versioned_docs/version-1.x/index.mdx, doc-sdk-rust_versioned_sidebars/version-1.x-sidebars.json
=> Issue #687 - Fix missing links in multiple SDK pages

doc-surrealdb_versioned_docs/version-2.x/surrealql/functions/database/rand.mdx
Related to https://github.com/surrealdb/surrealdb/pull/4384
=> Chore: Update rand functions documentation  for `UUID` and `ULID`

doc-surrealdb_versioned_docs/version-1.x/integration/rpc.mdx, doc-surrealdb_versioned_docs/version-2.x/integration/rpc.mdx
https://github.com/surrealdb/surrealdb/pull/4373
=> Update RPC use method

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/array.mdx, doc-surrealdb_versioned_docs/version-latest/tutorials/working-with-surrealdb-over-http-via-postman.mdx
Add #707 and #705 from @Readysoon  and @cobaltburn into main
=> Add #707 and #705 into main

doc-surrealdb_versioned_docs/version-latest/faqs/known-issues.mdx
**Ref:**
- Conversation in https://github.com/surrealdb/docs.surrealdb.com/issues/698
Thanks!
=> Add issue number in known issues page

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/access/index.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/access/jwt.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/access/record.mdx
Related to https://github.com/surrealdb/surrealdb/pull/4385
=> Chore: Update `AUTHENTICATE` clause  in `DEFINE ACCESS`

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/begin.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/cancel.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/commit.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/transactions.mdx
Review of all pages on statements related to transactions.
=> Transaction statements review

doc-surrealdb_versioned_docs/version-latest/surrealql/datamodel/records.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/select.mdx
https://github.com/surrealdb/surrealdb/pull/4443
=> Idiom destructuring syntax

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/string.mdx
https://github.com/surrealdb/surrealdb/pull/4462
=> Update `string::is::x` docs

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/session.mdx
=> DOC 231: Update function descriptions for `session::x`

doc-surrealdb_versioned_docs/version-latest/surrealql/datamodel/closures.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/array.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/count.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/duration.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/index.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/meta.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/object.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/parse.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/string.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/type.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/operators.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/let.mdx
Introduction to how to call functions using the traditional method as well as the new method syntax in SurrealDB 2.0.
Also adds a chart with an example of a function for each module / package.
closes #747
=> Method syntax and chaining

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/access/jwt.mdx, doc-surrealdb_versioned_docs/version-latest/tutorials/integrate-auth0-as-authentication-provider.mdx
Related:
https://github.com/surrealdb/surrealdb/issues/4487
https://github.com/surrealdb/surrealdb/pull/4488
https://github.com/surrealdb/surrealdb/pull/4493
=> Consider multiple token audiences in documentation

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/access/jwt.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/access/record.mdx
Explain that the JWKS feature requires the network capability and link to JWKS documentation from RECORD access page.
=> Clarify how JWKS works and where to learn more

doc-surrealdb_versioned_docs/version-latest/surrealql/parameters.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/create.mdx
Review of the entire CREATE statement page. Most of the query statements (CREATE/UPDATE/DELETE and all the rest) are pretty large so will make each one of them into their own PR.
=> Create statement review

doc-surrealdb_versioned_docs/version-latest/installation/upgrading/_category_.json, doc-surrealdb_versioned_docs/version-latest/installation/upgrading/beta.mdx, doc-surrealdb_versioned_docs/version-latest/installation/upgrading/index.mdx, doc-surrealdb_versioned_docs/version-latest/introduction/concepts/_category_.json, doc-surrealdb_versioned_docs/version-latest/introduction/start.mdx
Related to https://github.com/surrealdb/surrealdb/pull/4581
=> DOC-245: Add upgrading guide for SurrealDB 2.0.0-beta

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/indexes.mdx
https://github.com/surrealdb/surrealdb/pull/4480
=> Documents DEFINE INDEX ... CONCURRENTLY

doc-surrealdb_versioned_docs/version-latest/surrealql/datamodel/closures.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/array.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/count.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/index.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/meta.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/record.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/search.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/session.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/sleep.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/string.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/time.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/type.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/value.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/vector.mdx
Adds documentation and examples for the newest functions record::exists, value::diff, value::patch, as well as the recently added chain and map functions that take closures.
=> New 2.0 functions

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/table.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/update.mdx
Adds an import to allow deploy to work, fixes one typo.
=> Fix to build + typo

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/select.mdx
This commit changes "unicode" to the proper case "Unicode"
=> docs-Proofreading, change "unicode" to "Unicode"

doc-surrealdb_versioned_docs/version-latest/surrealql/demo.mdx
=> DOC-248: Update the Demo dataset URL

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/math.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/vector.mdx
Fixes a typo and some broken function links.
=> Small typo and broken link fixes

doc-surrealdb_versioned_docs/version-latest/installation/running/env_vars.mdx
Added in https://github.com/surrealdb/surrealdb/pull/4669 and https://github.com/surrealdb/surrealdb/pull/4670
=> Add new env vars for 2.0.0-beta2

doc-surrealdb_versioned_docs/version-latest/cli/version.mdx
`surreal version` has the option to find the version of a remote server, as pointed out by TheUnknown yesterday.
=> Add command options to surreal version

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/time.mdx
https://github.com/surrealdb/surrealdb/pull/4671
=> Chore: Add time is leap year function

doc-surrealdb_versioned_docs/version-latest/integration/rpc.mdx
=> DOC-192: Improve PRC documentations 

doc-surrealdb_versioned_docs/version-latest/installation/running/env_vars.mdx
Found a lot more env vars that pertain to CLI commands so have added them in a new section.
=> More env vars

doc-surrealql_versioned_docs/version-latest/datamodel/futures.mdx
=> fix: improve age calculation algo in `future` page

doc-surrealql_versioned_docs/version-latest/statements/create.mdx
https://surrealdb.com/docs/surrealql/statements/create
has duplicate content
=> fix: remove duplicate content on create statement

doc-surrealdb_versioned_docs/version-latest/cli/start.mdx, doc-surrealql_versioned_docs/version-latest/statements/create.mdx, doc-surrealql_versioned_docs/version-latest/statements/select.mdx
Additionally, show support for VERSION clause in SELECT and CREATE
Closes https://github.com/surrealdb/surrealdb/issues/4709
=> DOC-258: Add SurrealKV section in start CLI section 

doc-surrealdb_versioned_docs/version-latest/integration/http.mdx, doc-surrealdb_versioned_docs/version-latest/querying/surrealql/http.mdx
Changes the "ns" and "db" headers to the new format ("surreal-ns" and "surreal-db") along with some other minor changes.
=> Http protocol page improvements

doc-surrealdb_versioned_docs/version-latest/introduction/mongo.mdx, doc-surrealdb_versioned_docs/version-latest/introduction/neo4j.mdx, doc-surrealdb_versioned_docs/version-latest/introduction/sql.mdx, doc-surrealist_versioned_docs/version-2.x/concepts/sending-queries.mdx, doc-surrealql_versioned_docs/version-latest/datamodel/literals.mdx, doc-surrealql_versioned_docs/version-latest/statements/define/field.mdx, doc-surrealql_versioned_docs/version-latest/statements/define/table.mdx, doc-surrealql_versioned_docs/version-latest/statements/delete.mdx, doc-surrealql_versioned_docs/version-latest/statements/info.mdx, doc-surrealql_versioned_docs/version-latest/statements/insert.mdx, doc-surrealql_versioned_docs/version-latest/statements/kill.mdx, doc-surrealql_versioned_docs/version-latest/statements/live_select.mdx, doc-surrealql_versioned_docs/version-latest/statements/relate.mdx, doc-surrealql_versioned_docs/version-latest/statements/select.mdx, doc-surrealql_versioned_docs/version-latest/statements/show.mdx
PR to continue the work on improving the pages on statements. This one includes:
* DELETE
* INFO
* INSERT
* KILL
* RELATE
* SELECT
* LIVE SELECT (renamed from LIVE)
* SHOW
Also adds a small note into DEFINE TABLE about trickiness in specifying a timestamp / specifying a version number instead which will be able to 
closes https://github.com/surrealdb/docs.surrealdb.com/issues/680
=> More statements: DELETE, INFO, INSERT, KILL, RELATE, SELECT, SHOW

doc-surrealql_versioned_docs/version-latest/functions/database/crypto.mdx
=> Update Blake3 crypto function

src/content/doc-surrealist/troubleshooting.mdx
- Rename "Resetting the config"
- Explain log files
- Connection issues & troubleshooting
- Fixed Windows paths
=> Improve surrealist troubleshooting

src/content/doc-surrealdb/integration/rpc.mdx
- Minor changes to wording
- Fixed some inaccuracies
=> Fix some RPC docs content

src/content/doc-surrealdb/installation/running/env_vars.mdx
These two new environment variables were added in https://github.com/surrealdb/surrealdb/pull/4787.
=> Add two new env vars on parsing depth

src/content/doc-surrealdb/introduction/start.mdx
=> Change `author` table to `person` table

src/content/doc-surrealdb/installation/windows.mdx
As a future reference for https://discord.com/channels/902568124350599239/970338835990974484/1289321298417287292
=> feat: add troubleshooting section to the windows install page

src/content/doc-surrealql/statements/define/event.mdx
=> DOC-275: Minor update to `DEFINE EVENT`

src/content/doc-surrealql/datamodel/arrays.mdx, src/content/doc-surrealql/datamodel/casting.mdx, src/content/doc-surrealql/datamodel/sets.mdx
Improvements to the pages on casting, arrays, and sets.
=> Improvement: arrays, casting and sets in Data model 

src/content/doc-sdk-php/core/data-querying.mdx
While browsing through the docs i found a little syntax error
=> Fix PHP Syntax

src/content/doc-surrealql/datamodel/geometries.mdx
=> Correct format for [Lat,long]

src/util/rehypeCodemirrorPlugin.mjs
PHP code highlighting didn't work at all. This pull request fixes that
=> PHP code highlighting fix

src/content/doc-sdk-javascript/data-types.mdx, src/content/doc-sdk-php/data-types.mdx, src/content/doc-surrealdb/integration/cbor.mdx, src/content/doc-surrealql/datamodel/geometries.mdx
Point is structured as (lon, lat)
=> Fix incorrect point format

src/content/doc-sdk-javascript/methods/create.mdx, src/content/doc-sdk-javascript/methods/delete.mdx, src/content/doc-sdk-javascript/methods/insert.mdx, src/content/doc-sdk-javascript/methods/merge.mdx, src/content/doc-sdk-javascript/methods/patch.mdx, src/content/doc-sdk-javascript/methods/select.mdx, src/content/doc-sdk-javascript/methods/update.mdx
=> Fix RecordID links

src/content/doc-surrealql/datamodel/idioms.mdx
Adds a few examples on destructuring with an alias vs. regular AS aliasing. Closes https://github.com/surrealdb/docs.surrealdb.com/issues/995
=> Add bit on destructuring with an alias

src/content/doc-surrealql/functions/database/array.mdx, src/content/doc-surrealql/statements/for.mdx
Documentation for array::fold() and array::reduce() https://github.com/surrealdb/surrealdb/pull/4886
Closes https://github.com/surrealdb/docs.surrealdb.com/issues/891
=> Add array::fold, array::reduce() documentation

src/content/doc-surrealql/statements/define/analyzer.mdx
PR on SurrealDB:
https://github.com/surrealdb/surrealdb/pull/4995
Page updated:
https://deploy-preview-981--surrealdb-docs.netlify.app/docs/surrealql/statements/define/analyzer/#mapperpath
=> Documents filter/mapper

src/content/doc-surrealql/datamodel/datetimes.mdx
Fix some small typos in datetimes.mdx
=> fix: fix typos in datetimes.mdx

src/content/doc-surrealql/datamodel/idioms.mdx
Fix aliases used in explanation to match statement
=> Fix explanation in Graph navigation

src/content/doc-cloud/advanced-topics/migrating-data.mdx, src/content/doc-surrealdb/installation/upgrading/migrating-data-to-2.x.mdx
Small clarification that exports are SurrealQL, not actual SQL.
=> Clarify: SurrealQL, not SQL

src/content/doc-cloud/connect/sdk.mdx, src/content/doc-sdk-dotnet/installation.mdx
=> fix: update cloud connect example for .NET SDK

src/content/doc-surrealdb/querying/surrealql/surrealist.mdx, src/content/doc-surrealist/getting-started.mdx
Two notes to ensure that users know that the Sandbox is just for playing around and is limited to a single thread.
=> Add caveats about the Sandbox

src/content/doc-surrealql/statements/create.mdx, src/content/doc-surrealql/statements/insert.mdx, src/content/doc-surrealql/statements/relate.mdx, src/content/doc-surrealql/statements/update.mdx
Adds some examples of the recently discovered RETURN VALUE clause. Closes https://github.com/surrealdb/docs.surrealdb.com/issues/1047
=> Add examples of RETURN VALUE

src/content/doc-surrealdb/cli/env.mdx, src/content/doc-surrealdb/cli/start.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/5120
=> +Two new CLI commands and env vars for imports on startup

src/content/doc-surrealdb/integration/cbor.mdx, src/content/doc-surrealdb/integration/http.mdx, src/content/doc-surrealdb/integration/index.mdx, src/content/doc-surrealdb/integration/rpc.mdx, src/content/doc-surrealdb/integration/sdks.mdx
The integration documentation was lacking some subtle details and consistency
=> Improve integration documentation

src/content/doc-surrealql/datamodel/ids.mdx
Adds two examples of how to create an auto-incrementing ID.
=> Add two exampes of auto-incrementing IDs

src/content/doc-surrealql/statements/select.mdx
@kearfy remarked that this example didn't make a lot of sense when using it as a code snippet on socials, so updating it to a analytical SQL example from the fundamentals course.
=> Update Let example in docs

src/pages/index.astro
Update .NET SDK description to reflect its current features.
=> Update .NET SDK description

src/content/doc-surrealdb/cli/env.mdx
Adds two env vars related to telemetry.
=> Add two telemetry env vars

src/content/doc-surrealdb/integration/http.mdx, src/content/doc-surrealql/functions/database/http.mdx
Related to https://github.com/surrealdb/surrealdb/pull/5325
=> Add HTTP database function Improvements 

src/content/doc-surrealql/statements/relate.mdx
Aims to answer the frequently seen question "How do I see all relations between two records?"
=> Show all relations between two records

src/content/doc-surrealdb/reference-guide/observability.mdx, src/content/doc-surrealdb/reference-guide/security-best-practices.mdx, src/content/doc-surrealdb/reference-guide/vector-search.mdx, src/content/doc-surrealql/functions/database/time.mdx
This adds a page explaining how to turn on observability and which metrics are present.
=> Add observability page

src/content/doc-sdk-java/installation.mdx, src/content/doc-sdk-java/start.mdx, src/content/doc-surrealql/statements/create.mdx
Change log:
https://github.com/surrealdb/surrealdb.java/blob/main/CHANGELOG.md#021---2025-01-14
Release:
https://github.com/surrealdb/surrealdb.java/releases/tag/v0.2.1
=> Release Java SDK 0.2.1

src/content/doc-surrealdb/cli/start.mdx, src/content/doc-surrealdb/querying/graphql/http.mdx, src/content/doc-surrealdb/querying/graphql/surrealist.mdx, src/content/doc-surrealql/datamodel/references.mdx, src/content/doc-surrealql/statements/define/access/bearer.mdx, src/content/doc-surrealql/statements/define/config.mdx
https://github.com/surrealdb/surrealdb/pull/5394
=> Update experimental tags for `graphql`, `bearer_access` and `record_references` 

src/content/doc-sdk-javascript/core/utilities.mdx
=> DOC-287: Document append method

src/content/doc-surrealql/datamodel/records.mdx
=> Add note to use embedded records

src/content/doc-surrealql/statements/relate.mdx, src/content/doc-surrealql/statements/select.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/5424
=> Graph clauses

src/content/doc-surrealql/functions/database/object.mdx
Fixes a tag so that the function name can be clicked on to scroll down.
=> Fix function scroll down tag

src/content/doc-sdk-python/index.mdx
Update python required version, spotted by Lex that it was forgotten to update previously
https://discord.com/channels/902568124350599239/1013528064023601303/1334763335668994088
=> Update python required version

src/content/doc-cloud/index.mdx, src/content/doc-surrealdb/index.mdx, src/content/doc-surrealist/index.mdx, src/content/doc-surrealist/installation.mdx, src/styles/colors.scss
- Also merged two adjacent links
=> Fix button inconsistencies and positioning

src/content/doc-surrealql/statements/let.mdx
Adds advice that using typed LET statements at each step of the way is a good way to get better error messages and verifications at each step of the way when doing something complex.
=> Add some advice on using typed LET

src/content/doc-surrealdb/cli/env.mdx, src/content/doc-surrealql/functions/database/rand.mdx, src/content/doc-surrealql/functions/database/type.mdx
Adds three items that are in the 2.2 release notes but not documented yet.
=> Add three missing items

src/content/doc-surrealdb/installation/running/tikv.mdx
=> Update TIKV command

src/components/Search.astro, src/components/Sidebar/index.astro, src/components/layout/Navbar/Navbar.astro
- Fix: Search input wasn't focussed when shortcut was pressed.
=> Doc 351: Fix Search shortcut trigger

src/content/doc-surrealdb/cli/env.mdx
https://github.com/surrealdb/surrealdb/pull/5221
=> Add `SURREAL_MEMORY_THRESHOLD`

src/content/doc-sdk-rust/methods/new.mdx, src/content/doc-sdk-rust/setup.mdx
Adds examples of capabilities in the Rust SDK, including experimental ones added in https://github.com/surrealdb/surrealdb/pull/5563
=> Experimental capabilities in the Rust SDK

src/content/doc-surrealdb/cli/env.mdx
Fixes two env vars, h/t to Lucy:
https://discord.com/channels/902568124350599239/1181598754122518642/1344745996470452377
=> Fix backward env vars

package.json, src/content/doc-surrealql/functions/database/string.mdx
closes https://github.com/surrealdb/docs.surrealdb.com/security/dependabot/43
=> Fix broken link & dependabot alert 

src/content/doc-surrealql/statements/ifelse.mdx
closes https://github.com/surrealdb/docs.surrealdb.com/issues/1202
=> DOC-366: Fix syntax highlighting

src/content/doc-surrealdb/reference-guide/performance-best-practices.mdx
Adding an intial performance best practices page that we can incrementally add to over time.
=> Initial performance best practice page

src/content/doc-surrealql/statements/delete.mdx
Add the FROM keyword to the DELETE documentation
=> Add FROM keyword to DELETE docs

src/content/doc-surrealdb/reference-guide/performance-best-practices.mdx
Adding Surreal Cloud info and fix minor selling issues
=> Adding Surreal Cloud info and fix minor selling issues

src/content/doc-surrealql/statements/define/access/record.mdx
spelling correction: verifyier -> verifier
=> Correct record.mdx mispelling

src/content/doc-surrealql/statements/define/field.mdx
Adds some more info and examples on how individual object fields can be defined, as well as individual items inside an array.
closes #1186
=> DOC-357: More on defining object fields and array items

src/content/doc-surrealql/datamodel/geometries.mdx, src/content/doc-surrealql/datamodel/index.mdx
=> Add correct type for LineString

src/content/doc-surrealdb/deployment/azure.mdx, src/content/doc-surrealdb/deployment/google.mdx, src/content/doc-surrealdb/deployment/kubernetes.mdx, src/content/doc-surrealdb/introduction/concepts/namespace.mdx, src/content/doc-surrealql/statements/create.mdx, src/content/doc-surrealql/statements/info.mdx, src/content/doc-tutorials/working-with-surrealdb-over-http-via-postman.mdx
Updates the output for INFO statements, which now contain a lot more information.
=> Update output for INFO statements

src/content/doc-surrealql/datamodel/futures.mdx
Adds two tips for futures:
* A future defined using a statement needs parentheses
* Make sure to avoid possible infinite recursion
=> Add some future advice

src/content/doc-surrealql/statements/insert.mdx
Improve the INSERT IGNORE to describe its behavior more explicitly
=> Improve INSERT IGNORE section

src/content/doc-surrealql/clauses/split.mdx, src/content/doc-surrealql/statements/select.mdx
SPLIT is especially neat when turning collected paths into more structured data. Adds an example on that + links to the clauses page for the clauses that are only used in SELECT statements.
=> More on split

src/content/doc-surrealdb/models/time-series.mdx
Improvements to the timeseries page.
=> Improve timeseries page

src/content/doc-surrealql/statements/select.mdx
Small clarification that WHERE is a truthiness check and not strictly a boolean.
=> Make clear that WHERE is a truthiness check and not strict boolean

src/content/doc-surrealdb/reference-guide/graph_relations.mdx, src/content/doc-surrealql/statements/relate.mdx
Following my own advice here https://github.com/surrealdb/docs.surrealdb.com/pull/1270 to restructure some existing complex array ID examples.
=> Improve complex array IDs to make them ideal for record range queries

src/content/doc-sdk-python/concepts/data-maniplulation.mdx, src/content/doc-sdk-python/methods/delete.mdx, src/content/doc-sdk-python/methods/patch.mdx, src/content/doc-sdk-python/methods/select.mdx
There where javascript reference links used on the python page, I've changed this to python.
=> Fixed wrong links on python page.

src/content/doc-surrealql/datamodel/idioms.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/5821
=> Better destructuring examples

src/content/doc-surrealql/statements/info.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/5817
=> Add upcoming INFO as subquery feature

src/content/doc-surrealdb/cli/env.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/5804
=> Add SURREAL_BUCKET_FOLDER_ALLOWLIST env var

src/content/doc-surrealql/functions/database/rand.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/5772
=> Updates for rand::time

src/content/doc-surrealql/datamodel/arrays.mdx, src/content/doc-surrealql/datamodel/objects.mdx, src/content/doc-surrealql/functions/database/array.mdx, src/content/doc-surrealql/functions/database/object.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/5816
=> Add new object and array functions + operators

src/content/doc-surrealql/statements/kill.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/5876
=> Add new KILL notification

src/content/doc-surrealql/functions/database/duration.mdx, src/content/doc-surrealql/functions/database/rand.mdx, src/content/doc-surrealql/functions/database/time.mdx
More documentation for https://github.com/surrealdb/surrealdb/pull/5772
=> Documentation for new time functions and consts

src/content/doc-surrealql/statements/define/analyzer.mdx
Looks like `DEFINE ANALYZER` can also take a user-defined function.
=> Add example of define analyzer with function

src/content/doc-surrealql/statements/create.mdx, src/content/doc-surrealql/statements/select.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/5129
=> Examples of computed VERSION value

src/components/pages/labs/LabItem.astro, src/styles/global.scss
- increase width checkmark of input with type checkbox
- checkmark is now centered in input with type checkbox
- reverse gradient on the cards in SurrealDB Labs
=> DOC-492: SurrealDB Labs UI fix and change

src/content/doc-surrealql/parameters.mdx, src/content/doc-surrealql/statements/let.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/6023
(Also small rewording on another related page)
=> Change to show soon-to-be-deprecated LET syntactic sugar

src/content/doc-integrations/Embeddings/mistral.mdx, src/content/doc-integrations/Embeddings/openai.mdx
Adds a new tab to the Mistral page to show an integration using Rust. (Commit message mistakenly says Python but it's not 😆)
Also added OpenAI.
=> Add Mistral and OpenAI Rust integration

src/content/doc-surrealql/datamodel/geometries.mdx
- Changed `Line` to `LineString`
=> Fix LineString example

src/content/doc-surrealql/datamodel/futures.mdx
=> Use parent variable in futures when statement is wrapped in parentheses

package.json, scripts/make-llms-txt.ts
- Able to generate llms.txt and llms-full.txt files
- There are some caveats regarding the use of description for each link. But think it's fine for it's initial mvp implementation. We can further iterate on the implementation.
Referenced issue: #1286
=> Automation of llms.txt file

src/content/doc-surrealql/functions/database/crypto.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/5959
=> Add crypto::joaat

src/content/doc-surrealql/statements/use.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/6214
=> New use statement behaviour

src/content/doc-surrealdb/cli/env.mdx, src/content/doc-surrealdb/reference-guide/graph-relations.mdx, src/content/doc-surrealdb/reference-guide/sample-industry-schemas.mdx, src/content/doc-surrealql/datamodel/futures.mdx, src/content/doc-surrealql/parameters.mdx, src/content/doc-surrealql/statements/define/field.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/6347
=> Add examples of parameterized statements

src/content/doc-surrealql/datamodel/casting.mdx, src/content/doc-surrealql/datamodel/index.mdx, src/content/doc-surrealql/functions/database/index.mdx, src/content/doc-surrealql/operators.mdx
Fixed some inconsistent and broken tables
- Avoid wrapping
- Consistent paragraph parsing
- Removed duplicate IN/NOT IN operator table rows
=> Fix table column width
