surrealdb/docs.surrealdb.com

docs/surrealql/functions/math.mdx, docs/surrealql/functions/type.mdx, versioned_docs/version-nightly/surrealql/functions/math.mdx, versioned_docs/version-nightly/surrealql/functions/type.mdx
In certain places around the docs, `<` characters were displayed incorrectly (due to the conversion from Ember.js to Docusaurus). This fix ensures all `array{{ "<" }}` code is replaced with `<`.
Closes #118.
=> Ensure `<` characters are displayed correctly

docs/integration/http.mdx, versioned_docs/version-nightly/integration/http.mdx
Removes an unused header from the HTTP integration page, and fixes header link ids, for in-page navigation.
=> Remove unused header from HTTP integration page

docs/surrealql/statements/define/token.mdx
Document that the `exp` token claim is always required and the `nbf` claim is always verified. [Source](https://github.com/surrealdb/surrealdb/blob/bc4ffcb4cf53a400287c864bc6121d9b1d7ea01c/lib/src/iam/verify.rs#L166-L179).
=> Improve documentation of `exp` and `nbf` token claims

src/theme/SearchBar/index.tsx, src/theme/SearchBar/search.ts
Due to an issue in the query planner, the score of every result would be zero. Solutino for the moment is to match the hostname on the clientside.
Additionally, we now match the version from the current URL against the url in the search result to guarantee correct and no duplicate results, and it could sometimes happen that an older search query would overwrite a newer one. This is fixed too
=> Fix search

src/theme/SearchBar/search.ts
because we need to filter hostname and version on the frontend temporarily, we need to increase the search limit to get enough relevant results
=> increase search limit

docs/surrealql/datamodel/geometries.mdx
Pretty certain copy-pasta from preceding in documentation example crept in
=> Fix mistake in geomterics data model documentation

docs/embedding/rust.mdx
Fixed a typo in the word merge. The example had the example written, ".update().nerge()", when the correct text would be, ".update().merge()".
=> Fixed typo in Rust SDK Update examples

docs/surrealql/statements/define/database.mdx, docs/surrealql/statements/define/event.mdx, docs/surrealql/statements/define/field.mdx, docs/surrealql/statements/define/function.mdx, docs/surrealql/statements/define/namespace.mdx, docs/surrealql/statements/define/param.mdx, docs/surrealql/statements/define/scope.mdx, docs/surrealql/statements/define/table.mdx, docs/surrealql/statements/define/user.mdx, versioned_docs/version-1.1.0/surrealql/statements/define/database.mdx, versioned_docs/version-1.1.0/surrealql/statements/define/event.mdx, versioned_docs/version-1.1.0/surrealql/statements/define/field.mdx, versioned_docs/version-1.1.0/surrealql/statements/define/function.mdx, versioned_docs/version-1.1.0/surrealql/statements/define/namespace.mdx, versioned_docs/version-1.1.0/surrealql/statements/define/param.mdx, versioned_docs/version-1.1.0/surrealql/statements/define/scope.mdx, versioned_docs/version-1.1.0/surrealql/statements/define/table.mdx, versioned_docs/version-1.1.0/surrealql/statements/define/user.mdx, versioned_docs/version-nightly/surrealql/statements/define/database.mdx, versioned_docs/version-nightly/surrealql/statements/define/event.mdx, versioned_docs/version-nightly/surrealql/statements/define/field.mdx, versioned_docs/version-nightly/surrealql/statements/define/function.mdx, versioned_docs/version-nightly/surrealql/statements/define/namespace.mdx, versioned_docs/version-nightly/surrealql/statements/define/param.mdx, versioned_docs/version-nightly/surrealql/statements/define/scope.mdx, versioned_docs/version-nightly/surrealql/statements/define/table.mdx, versioned_docs/version-nightly/surrealql/statements/define/user.mdx
The `DEFINE EVENT statement` page had a misspelling of `usuage` -> `usage`, and I removed the trailing space.
Note: This is my second attempt at this PR because the first time I didn't realize that a vscode extension was mucking everything up :)
=> Docs: fix spelling

src/components/SDK/sdks_container.mdx
Fix alt tag for ember icon and replace nest.js icon correct image instead of nuxt's icon
=> Fix icons on docs SDKs page

docs/surrealql/statements/select.mdx
The comment reads `--force the usage of the table iterator` but according to the doc above, that should require the keyword `NOINDEX,` not `idx_name` as currently shown.
=> Fix typo for WITH NOINDEX example

docs/surrealql/statements/define/user.mdx
This may be intentional, but I believe this is a typo.
=> fix: typo `DEFINE TOKEN` to `DEFINE USER`

docs/surrealql/datamodel/futures.mdx
The date doesn't get automatically parsed as a datetime, since it lacks a time component. This will result in an error when attempting to add the duration to the string. Including the explicit cast to a datetime fixes it.
[Fixes #3235](https://github.com/surrealdb/surrealdb/issues/3235)
=> Fixed future example

docs/integration/sdks/nodejs.mdx
I was trying the example from the website and getting this error: 
`[Error: data did not match any variant of untagged enum Credentials`
as it turns out the params name from the website is incorrect
=> Fix nodejs `db.signin()` example

docs/intro.mdx, package.json, pnpm-lock.yaml, src/components/GiscusComponent/index.tsx
It adds Giscus to our Docs. 
The way to add Github comments to any page is:
1. Make sure you add:
enableComments: true on top. Something like:
---
sidebar_position: 1
pagination_next: null
enableComments: true
---
2. import the component
import GiscusComponent from '@site/src/components/GiscusComponent';
3. Add the component to the bottom of the page
<GiscusComponent />
=> feat(giscus): Adds Giscus to docs

docusaurus.config.js
The GH icon the site goes to surrealdb org rather than the official GH docs repo. Adding a minor change to update the link.
=> Updating GH Repo link on docs site

versioned_docs/version-1.0.x/surrealql/statements/select.mdx, versioned_docs/version-1.1.x/surrealql/statements/select.mdx, versioned_docs/version-nightly/surrealql/statements/select.mdx
In the SELECT SurrealQL Syntax example in the select.mdx documents on line 27 there was an excess bracket
=> removed excess bracket in select.mdx files

versioned_docs/version-1.0.x/surrealql/datamodel/casting.mdx, versioned_docs/version-1.1.x/surrealql/datamodel/casting.mdx, versioned_docs/version-nightly/surrealql/datamodel/casting.mdx
Remove examples that don't parse correctly. 
Ties to https://github.com/surrealdb/surrealdb/issues/3046  and https://github.com/surrealdb/surrealdb/issues/2907
=> Docs: Update type casting examples 

src/theme/NotFound.js
It redirects the 404 page errors to the last known path, so for example if a user types:
https://docs.surrealdb.com/docs/installation/macos/sdsdsd
it will go to 
https://docs.surrealdb.com/docs/installation/macos
If the user types a complete random route it redirects to our main url:
https://docs.surrealdb.com/docs/intro
=> feat(404page): It redirects to last known path

versioned_docs/version-1.1.x/integration/sdks/dotnet.mdx, versioned_docs/version-1.2.x/integration/sdks/dotnet.mdx, versioned_docs/version-nightly/integration/sdks/dotnet.mdx
This PR does the following: 
- Added a TABLE variable in the example
- Introduces RawQuery and LiveRawQuery functions
- Adds examples for `db.Query` and `db.LiveQuery`
=> Update .NET SDK documentation for v0.4.0

versioned_docs/version-1.0.x/surrealql/functions/string.mdx, versioned_docs/version-1.1.x/surrealql/functions/string.mdx, versioned_docs/version-1.2.x/surrealql/functions/string.mdx, versioned_docs/version-nightly/surrealql/functions/string.mdx
Closes #327, closes https://github.com/surrealdb/surrealdb/issues/3463
This commit corrects a documentation error where `string::is::format` was listed instead of the actually implemented `string::is::datetime`. The change aligns the documentation with the codebase and clarifies the available string functions.
=> fix: replace `string::is::format` with `string::is::datetime`

versioned_docs/version-1.0.x/installation/windows.mdx, versioned_docs/version-1.1.x/installation/windows.mdx, versioned_docs/version-1.2.x/installation/windows.mdx, versioned_docs/version-nightly/installation/windows.mdx
Removes Installing SurrealDB using Chocolatey as the versioning is not officially supported by SurrealDB. The latest version it has is v1.0.0-beta.9 
Similar PR for website [#477](https://github.com/surrealdb/www.surrealdb.com/pull/477)
=> Docs: Update SurrealDB installation instructions for Windows

versioned_docs/version-1.0.x/integration/sdks/nodejs.mdx, versioned_docs/version-1.1.x/integration/sdks/nodejs.mdx, versioned_docs/version-1.2.x/integration/sdks/nodejs.mdx, versioned_docs/version-nightly/integration/sdks/nodejs.mdx
`Http` and `Https` connects aren't available yet for the Node SDK causing this error: 
```
error: There was a problem with the underlying datastore: Cannot connect to the `HTTP` remote engine as it is not enabled in this build of SurrealDB
code: "GenericFailure"
```
This PR Removes the option from the docs and also adds a note 
Resolves #317
=> Update SurrealDB SDK connection to use WebSockets

versioned_docs/version-1.0.x/deployment/kubernetes.mdx, versioned_docs/version-1.1.x/deployment/kubernetes.mdx, versioned_docs/version-1.2.x/deployment/kubernetes.mdx, versioned_docs/version-nightly/deployment/kubernetes.mdx
The commands in code block were together with the outputs which will throw and error in terminal. 
This PR separates the commands from the outputs.
=> Docs: Separate commands in Kubernetes deployment guide

versioned_docs/version-1.2.x/surrealql/statements/define/field.mdx
This PR explains the code examples we have in Define field and also adds examples for permissions clause to address #151 and #145
closes #151 
closes #145
=> Docs: Add field type examples and permissions examples

Makefile
Ensures the documentation `sitemap.xml` file is uploaded on deployment. We will then use separate sitemaps for the base domain, and the documentation path.
=> Upload `sitemap.xml` file with deployment

versioned_docs/version-1.2.x/integration/sdks/nodejs.mdx
When I tried following the node.js sdk tutorial, I kept getting the following error:
```bash
ERROR [Error: data did not match any variant of untagged enum Credentials] {
code: 'InvalidArg'
}
```
This seems to have been caused by the following lines:
```ts
await db.signin({
user: 'root',
pass: 'root',
});
```
Reverting it back to 
```ts
await db.signin({
username: 'root',
password: 'root',
});
```
fixed the issue and lead to the desired behavior.
=> Docs: Update Nodejs sdk examples

versioned_docs/version-1.0.x/reference-guide/full-text-search.mdx, versioned_docs/version-1.1.x/reference-guide/full-text-search.mdx, versioned_docs/version-1.2.x/reference-guide/full-text-search.mdx, versioned_docs/version-nightly/reference-guide/full-text-search.mdx
Actually the documention is misleading
https://github.com/surrealdb/surrealdb/issues/3530
> In fact, the main usage of composite indexes is for unique indexes, when you want to ensure that there are not two records in the same table having the same composite content.
> 
> By extension, it is possible to build a composite index with FTS in SurrealDB, but that does not really make sense, as there is no possibility to query it. In a future release, we will clarify this behavior.
=> Replace composite index by two indexes for FTS

versioned_docs/version-nightly/surrealql/operators.mdx
This PR adds documentation for the KNN operator.
=> Add KNN operator to the list of operators

versioned_docs/version-nightly/surrealql/datamodel/ids.mdx
This PR adds a line in the numeric record-id section about the behaviour when record-id's overflow 64-bit signed integers.
=> Add documention about overflowing numeric record-ids

src/css/custom.scss
On windows 11 - 64bit When browsing on chrome there was a horizontal scrollbar showing. It seemed that the docusaurus adds a width with a defined variable as value. But the width is already defined on the parent `.theme-doc-sidebar-container`. So by unsetting the width on the  only div that lives inside `.doc-sidebar-container` fixes the scrollbar issue.
I have checked the issue against the browsers: `Firefox`, `Chrome`, `Brave` and `Edge` and it seems it's fixed. But not sure how it will affect Mac OSX.
Also note, the mobile version of the sidebar doesn't get affected at all by this change. At least on my android pixel 7 phone ( chrome )
=> fix: permanent horizontal scrollbar on sidebar

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/create.mdx
This page contains a `CREATE ONLY` example, but when reading it for the first time I didn't know how to create more than one record (tried an array, range, etc.) Comma-separated is doable so have added that example right before `CREATE ONLY` is mentioned.
=> Add example of multiple record type creation

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/relate.mdx
This PR started out as a quick change to the "Tobie's purchased products" bit to make it easier to read, but decided to add a bit more:
* Clarify that graph edges can be UPDATEd like any other table
* A small hint that whether -> and <- are `in` or `out` depends on their direction in relation to the graph edge. (Was something that tripped me up in the beginning as I was reading `->` as `in` and `<-` as `out` at first and couldn't make sense of the long graph query doing that)
One note is that the examples in this page sort of assume a strict schema (as otherwise the queries returning the same results wouldn't return the same result if multiple record types were found at `in` or `out`) and the example I added with a small synopsis is the same. Was considering explaining all of that …
=> Update relate query explanations

doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/geo.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/ml.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/object.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/parse.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/time.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/type.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/vector.mdx
Docusaurus auto adds emojis when special key words are written after a `::` which causes emojis. This PR adds a zero-width space to remove that behaviour.
=> Docs: Remove emoji characters

src/css/custom.scss
Removes the version tag from the sidebar only.
=> fix(doc-126-sidebar): It removes the version tag in the sidebar

doc-surrealdb_versioned_docs/version-1.x/deployment/fly.mdx
Seems like fly.io changed their cli. You need to use `--no-deploy` flag now to get the same behavior as before.
On a side note, you can not get a sweet web gui to make edits after launching the first time.
=> Update fly.mdx to match change in fly cli

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/indexes.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/relate.mdx
I noticed some interesting behaviour in RELATE today that seems good to add. Namely:
* You can't change the type of in and out,
* Specify that in and out can only be single values, but you can still use multiple values in RELATE, it will just create multiple graph edges equal to the product of the inputs
I chose the title Always two there are - no more, no less. Is that having too much fun for a documentation page? Could make this a drier title if so.
=> More info on RELATE behaviour

doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/parse.mdx
One function name here is incorrect.
=> Typo fix in function name

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/table.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/show.mdx
Adds an example of output for changefeeds in both the DEFINE TABLE and SHOW pages. Also:
* The new INCLUDE ORIGINAL option. ~~I got this to work in the CLI but Surrealist doesn't handle it yet so haven't added that to the output, but anyone should be able to use the same example and add INCLUDE ORIGINAL to see what it looks like so not too hard to see for oneself.~~ <-- Looks like I coincidentally got Surrealist to disconnect somehow and thought it couldn't handle INCLUDE ORIGINAL, but it can so have added the output of that.
* Changed the 1d to 3d. I misread that as `id` once or twice.
As an aside, getting a nice example for this took a while longer than expected as I wasn't able to use a parameter set in between the table creation and the changes:
```
DEFINE TABLE user CHANGEFEED 3d; …
```
=> Add example of output to changefeeds

doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/script/arguments.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/parameters.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/event.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/index.mdx
Inside the parameters page:
* Rewrites the intro and a bunch of other places
* Enlargens the original Tobie example to one in which setting a variable is useful
* Moves the reserved variable names out from a table into their own subsections with an example for each. Related ones are combined ($before and $after, $this and $parent)
After this the question is how to get people to notice the page (since parameters.mdx is pretty far down). Here adding an index.mdx to statements along with a quick blurb informing that statements have parameters floating around and a link to the full parameters page felt best.
=> Extra parameter info and examples

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/field.mdx
This PR lengthens the example using `FLEXIBLE` to show what happens when it is not included.
Also, I haven't been able to find another good use case for FLEXIBLE besides object types. Is there anything else? In the meantime I've changed the wording to suit this (from "especially useful" to "necessary") since I can't imagine anyone wanting a non-FLEXIBLE object type can only be empty on a SCHEMAFULL table.
=> Increase length of FLEXIBLE example to show behaviour without it

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/_category_.json, doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/index.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/info.mdx
* INFO FOR works for USER as well, but this isn't shown in the syntax (PR adds syntax)
* INFO and DEFINE are almost always counterparts to each other (with the exception of MODEL and LIVE, every item inside INFO has a matching DEFINE statement). Makes this point clear
* Adds examples of output for INFO
* Some formatting (including where DEFINE still needed an extra click because a separate page was specified in the category.json page)
* Some rewriting
=> Extra info examples, connect info and define pages

doc-surrealdb_versioned_docs/version-1.x/integration/sdks/nodejs.mdx
Running the nodejs example currently gives `TypeError: Surreal is not a constructor` because of a nonexistent default import. After changing to named import it works.
Resolves surrealdb/surrealdb.node#24
=> fix: nodejs example incorrect import

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/create.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/delete.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/relate.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/update.mdx
The current RETURN syntax inside CREATE, DELETE and UPDATE looks like this:
```
[ RETURN [ NONE | BEFORE | AFTER | DIFF | @projections ... ]
```
Some issues with this we noticed are:
* The square brackets after RETURN makes it looks like NONE the rest are option (i.e. that you can just use RETURN on its own)
* The word `projections` is pretty rarely used so doesn't give a good idea of what can be returned
* No indication that they can be divided by commas
* It's missing a closing `]`
The PR changes it to this which is longer but looked surprisingly clear when I gave a few other syntaxes a try.
```
[ RETURN NONE | RETURN BEFORE | RETURN AFTER | RETURN DIFF | RETURN @statement_param, ... ]
```
=> Rewrite RETURN syntax

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/sleep.mdx
The SLEEP page doesn't indicate at the moment in which cases it would be most useful. @emmanuel-keller  helpfully added a few and this PR is his comment almost verbatim.
=> Add some use cases for SLEEP

doc-surrealdb_versioned_docs/version-1.x/surrealql/datamodel/geometries.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/datamodel/index.mdx
"Line" is not an official GeoJson type, "LineString" ist the correct type. Using "Line" throws an error.
=> Fix wrong example for geometry<line>

doc-surrealdb_versioned_docs/version-1.x/surrealql/datamodel/casting.mdx
Following the issue #292, this PR aims to include <array<T>> and <record> casting in the documentation.
The issue also mentions detailing the `.bind` function in Rust's SDK, but since the time I wrote the issue to now I come to realize there isn't really anything wrong with this part of the documentation, but rather a misunderstand from my part three months ago.
=> Add documention about <array<T>> and <record> casting

src/components/SurrealistMini/index.tsx
The `&compact` parameter removes the Surrealist header from the embeds so it looks neater.
=> Docs: Update SurrealistMini component to include 'compact' parameter in URL

doc-surrealdb_versioned_docs/version-1.x/surrealql/datamodel/geometries.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/geo.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/operators.mdx
Some small fixes and updates for geo functions and types:
* The output for functions like centroid no longer look like JSON objects, but just a tuple of two points (though type::is::geometry still returns true for them)
* Changes some type names to match the GeoJSON names
* Fixes the Wyoming example (somehow has coordinates for somewhere in Europe)
* Output: Floats now have an f at the end
* Also small opinionated change: found some more geo examples on the operators page which work fine, but having SELECT * FROM everywhere where a simple RETURN would have worked seems needlessly verbose.
=> Geo updates and fixes

doc-surrealdb_versioned_docs/version-1.x/surrealql/datamodel/ids.mdx
A user here https://github.com/surrealdb/surrealdb/issues/3928 would like to see some more examples of querying on object-based records.
* You can treat their inner fields as record fields, which is pretty neat
* Range queries on them work in the same way as the array examples
Also changed the `temperature` records to `weather` records since they have a `temperature` field and querying on `temperature` table's `temperature` field feels weird.
Anything else interesting to add?
=> Add object-based record ID queries

doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/search.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/database.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/table.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/show.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/define/database.mdx
I noticed some tests today in the source code that had simple integers after `SINCE`, turns out that SHOW can show changes since a version stamp instead of a datetime! With that it's much easier to test out the behaviour (since you can't do something like `LET $time = time::now();` and then show `SINCE $now`).
Edit: Also noticed that DEFINE DATABASE doesn't show that a changefeed can be defined on the whole database, so added that.
=> SHOW on changefeed works with version stamp as well as datetime

doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/script/index.mdx
With a recent update to rquickjs ES2023 will now be supported in javascript functions in 2.0.
=> Update supported JavaScript specification.

doc-surrealdb_versioned_docs/version-1.x/integration/sdks/python.mdx
Changed the URL used in the Python Notebook example to use WebSockets and point it to the `/rpc` endpoint.
Fixes https://github.com/surrealdb/docs.surrealdb.com/issues/553
=> Fix URL for Python Notebook example

doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/type.mdx
Some typo fixes and related changes for the `type` functions page. The output has also changed in a few places (such as appending `dec` for a decimal) and points which now show up as a tuple of two items. Also cut the queries in type::field(s) to a single one that matches the output.
=> Correct type::field(s), other small changes/typo fixes

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/token.mdx, doc-surrealdb_versioned_docs/version-1.x/tutorials/integrate-auth0-as-authentication-provider.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/define/token.mdx, doc-surrealdb_versioned_docs/version-2.x/tutorials/integrate-auth0-as-authentication-provider.mdx
Updates the Auth0 tutorial to use [namespaced claims](https://auth0.com/docs/troubleshoot/product-lifecycle/past-migrations/custom-claims-migration#restricted-claims). Explains the current behavior of the `$token` parameter with regards to claims that were provided with a namespace prefix. Closes #543.
=> Require namespacing Auth0 claims and explain how

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/select.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/select.mdx
Small fix: this example probably intended to give the average age over these `person` records, not the combined total of years.
=> Change sum to mean for age in grouping example

doc-surrealdb_versioned_docs/version-1.x/surrealql/datamodel/datetimes.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/database/rand.mdx, doc-surrealdb_versioned_docs/version-1.x/surrealql/functions/script/type-conversion.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/datamodel/datetimes.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/functions/database/rand.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/functions/script/type-conversion.mdx
Since we don't have a `<time>` type in SurrealDB this page was a bit misleading.
=> Rename time.mdx to datetimes.mdx

doc-surrealdb_versioned_docs/version-1.x/tutorials/define-a-schema.mdx
'There was a problem with the database: Parse error: Failed to parse query at line 5 column 12 expected query to end
|
5 | ASSERT string::is::email($value);
|        ^ perhaps missing a semicolon on the previous statement?
'
=> Update define-a-schema.mdx to fix syntax error.

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/select.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/select.mdx
Found what is (I assume) a typo in an example that seems to be showing the use of NOINDEX but is actually specifying an index.
Also some small changes: spacing, changing genre to gender (genre is the correct word in French but I can't imagine a "genre" of employee), and putting the bullet points in the same order as the following examples.
=> Fix example needing NOINDEX

doc-surrealdb_versioned_docs/version-1.x/introduction/architecture.mdx
Correct 'minimum' typo in last paragraph.
=> Correct 'minimum' typo in Architecture Docs Page

doc-surrealdb_versioned_docs/version-1.x/tutorials/index.mdx, doc-surrealdb_versioned_docs/version-2.x/tutorials/index.mdx
Our new 'Define a Schema in SurrealDB' was listed on the contents on the left, but missing within the body of the Tutorials main page, adding it in here too.
=> Add 'Define a Schema in SurrealDB' to list of Tutorials

doc-sdk-rust_versioned_docs/version-1.x/setup.mdx, doc-surrealdb_versioned_docs/version-1.x/embedding/rust.mdx, doc-surrealdb_versioned_docs/version-2.x/embedding/rust.mdx
This PR will remove the NEW emoji and simply display text like it should:
=> fix: remove displayed new emoji

doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/define/access/record.mdx
Improve documentation by removing text that is no longer current, fixing some orthographic errors and considering the differences between `PERMISSIONS` and `AUTHENTICATE` for validating authorization conditions.
=> Improve record access documentation

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/let.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/let.mdx
In both versions of the documentation, the number 3 is accidentally introduced at the beginning of the description
=> Removed unwanted '3' char

doc-surrealdb_versioned_docs/version-1.x/introduction/start.mdx, doc-surrealdb_versioned_docs/version-2.x/introduction/start.mdx
This commit updates the 1.x and 2.x documentation, within the "Introduction" section, on the "Getting Started" page ("start.mdx"), making the following changes:
* Expands on the difference between the Surrealist app and the SurrealDB CLI.
* Replaces the phrase "the Surrealist" with "the Surrealist app".
* Adds links to the SurrealDB CLI documentation.
=> Docs: Clarify a bit more on SurrealQL running options in the getting started guide 

doc-sdk-javascript_versioned_docs/version-1.x/core/initialization.mdx
TS error
```
Block-scoped variable 'db' used before its declaration. 
surreal.ts(7, 11): 'db' is declared here.
Variable 'db' is used before being assigned.
```
=> fix: remove const keyword as it is causing scope issue

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/define/token.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/define/token.mdx
closes #660
In the 'Requirements' section, `DEFINE DATABASE` was used instead of `DEFINE TOKEN`.
=> Issue #660 - Replace DEFINE DATABASE with DEFINE TOKEN under Requirements

doc-sdk-javascript_versioned_docs/version-1.x/core/streaming.mdx
Fix for Issue #661 
CREATE was mistakenly used instead of DELETE.
=> Issue #661 - Fix the DELETE live action in the table

doc-surrealdb_versioned_docs/version-1.x/surrealql/statements/create.mdx, doc-surrealdb_versioned_docs/version-2.x/surrealql/statements/create.mdx
Small PR: Adds some simple examples of the pipe operator (e.g. CREATE |townsperson:5|) to the section on creating multiple records using the syntax.
=> Add example of pipe operator in CREATE

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/array.mdx
Small fix: array::pop() returns a value, not an array. (Looking at the discussion in Discord it looks like it (maybe) used to return an array until the behaviour was improved)
=> array::pop() returns a value, not an array

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/field.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/table.mdx
Slimming down a previous draft PR here https://github.com/surrealdb/docs.surrealdb.com/pull/702 to only add a section on both DEFINE TABLE and DEFINE FIELD to help users understand the interaction between the two.
Interesting behaviours:
* A DEFINE TABLE statement represents a template for a record that doesn't exist yet, which is why ASSERT can't be done here as a user might expect (so no ASSERT type::is::string($this.name) or somesuch)
* The parameter $this refers to a parent record inside a DEFINE FIELD statement. But a new user to databases may get confused by the term record and wonder if this means there is a DEFINE RECORD statement somewhere...on the other hand, experienced users won't like the term "parent table" since a table is a template and not something that holds actual …
=> Add section on interaction between fields to DEFINE FIELD/TABLE

doc-surrealdb_versioned_docs/version-latest/surrealql/datamodel/records.mdx
Page [Record links](https://surrealdb.com/docs/surrealdb/surrealql/datamodel/records).
Currently the sentence:
- "_Records ids can be stored directly within other records, either as top-level properties, or nested within objects or arrays._"
is included at the beginning of both sections:
- [Storing record links within records](https://surrealdb.com/docs/surrealdb/surrealql/datamodel/records#storing-record-links-within-records), and 
- [Fetching remote records from within records](https://surrealdb.com/docs/surrealdb/surrealql/datamodel/records#fetching-remote-records-from-within-records)
The first one appears as the correct one, as the example on how to store record links within records is discussed in this section. The one in the other section seems duplicate/redundant. This section can …
=> Remove duplicate sentence from records page

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/relate.mdx
Adds an example or two of how a graph query that includes multiple fields automatically gets returned in the same structure and might be preferable to using aliases.
=> Add example of graph query structure without aliases

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/sleep.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/break.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/continue.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/for.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/ifelse.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/let.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/return.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/sleep.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/throw.mdx
PR to review and improve statements for the ones I can only think of the word 'auxiliary' to describe them: they function in the context of a query but don't make queries themselves: BREAK, CONTINUE, FOR, IF ELSE, LET, RETURN, SLEEP, THROW.
Mostly these sorts of changes:
* More examples
* Try to avoid duplicate content in the header + intro
* Some rephrasing
* More links between pages
* Also added an example to the sleep function which can be used in a more dynamic way than the SLEEP statement.
Also note the syntax change in FOR, might be a better way to do it
=> Auxiliary statements review

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/array.mdx
Adds documentation for the array::windows function, which was added in https://github.com/surrealdb/surrealdb/pull/4445.
=> array::windows() documentation

doc-surrealdb_versioned_docs/version-latest/surrealql/demo.mdx
It seems like the fields of the `order` table in the [Surreal Deal Store demo](https://surrealdb.com/docs/surrealdb/surrealql/demo) have changed compared to the "mini" counterpart.
Running the query as is on the demo led to some empty fields (see screenshot below):
I cross-referenced the actual field names via the Surrealist Explorer (beautiful feature btw — is there a way to show this as a tab in the Query page?), and updated the field names:
Here's a PR with the updated query.
=> 📝 Update invalid fields in Surrealist demo

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/rand.mdx
From the code here: https://github.com/surrealdb/surrealdb/blob/3f5ef432481f4506feb5dc818281fce6c0f1e400/core/src/fnc/rand.rs#L45
=> docs(random): add doc for `rand::guid` with 2 args

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/field.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/table.mdx
Adds a quick note that the default permissions for table are NONE, but for field they are FULL.
Thanks @Xkonti for noticing!
=> Add info on default permissions

doc-surrealdb_versioned_docs/version-latest/installation/running/env_vars.mdx
Just a bland page with all the env vars I could find, as they are currently only found in the source code and users sometimes ask about them. This section looks like the best place to put it, but could easily go somewhere else.
=> Add page on env vars

doc-surrealdb_versioned_docs/version-latest/installation/running/memory.mdx
Fixed a typo in the login credentials of  the `Run a single-node, in-memory server` docs.
=> Typo in login credentials in memory server docs

doc-surrealdb_versioned_docs/version-latest/cli/start.mdx
Adds the SurrealKV backend (plus rocksdb) as well as an explanation of how to form the argument for the backend.
As an aside, what's the best way to make the part of the table with the new explanation a little prettier?
=> Add some explanation for positional argument in surreal start command

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/ifelse.mdx
This reference to the `$scope` variable in the IFELSE statements documentation slipped by when we updated after the change. This specific example is now only applicable to SurrealDB 2.X users.
=> Remove reference to legacy scopes from IFELSE docs

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/relate.mdx
This PR adds examples of the `<->` operator to query, which at the moment isn't in the documentation.
Also includes some advice on using an index to ensure that these relations can't be doubled by relating from one record to a second one, and then from the second one back to the first one again.
I wonder if bilateral is the right word here? The subject is a relation that exists between two equals, and thus could have been set as much from the first record as from the second.
=> Add examples of bilateral (equal?) relation querying

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/string.mdx
Small typo: should be match, not matches
=> Typo: ~ is the 'match' operator

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/event.mdx
This PR adds a section to the DEFINE EVENT documentation, noting how events don't perform any permission checks, allowing to run extra queries with system permissions.
=> Add section about how events work with permissions

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/table.mdx
Related to https://github.com/surrealdb/surrealdb/pull/4558
=> Docs: SCHEMAFULL table should be TYPE NORMAL by default

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/type.mdx
The `type::range` function now accepts a single argument, either a range or an array, to be converted into a record range. Closes https://github.com/surrealdb/surrealdb/issues/4639
=> DOC-246: Update `type::range` function example

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/array.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/bytes.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/count.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/crypto.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/duration.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/encoding.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/geo.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/http.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/index.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/math.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/meta.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/object.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/parse.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/rand.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/record.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/search.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/session.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/sleep.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/string.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/time.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/type.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/value.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/vector.mdx
This PR adds all the functions missing in the documentation, with the exception of those that have a path but haven't been implemented yet (e.g. vector::distance::mahalanobis)
Some of these are new to 2.0. Big thanks to @Odonno who has a separate PR for many new array functions that I used for this
* array::fill
* array::is_empty
* array::range
* array::repeat
* array::shuffle
* array::swap
* crypto::blake3
* session::ac
* session::rd
* vector::scale
Others are not new and were just missed:
* bytes::len
* math::pow
* parse::url::scheme
* string::matches
* time::ceil
=> Add missing functions

doc-surrealdb_versioned_docs/version-latest/cli/export.mdx, doc-surrealdb_versioned_docs/version-latest/cli/fix.mdx, doc-surrealdb_versioned_docs/version-latest/cli/help.mdx, doc-surrealdb_versioned_docs/version-latest/cli/import.mdx, doc-surrealdb_versioned_docs/version-latest/cli/isready.mdx, doc-surrealdb_versioned_docs/version-latest/cli/ml/_category_.json, doc-surrealdb_versioned_docs/version-latest/cli/sql.mdx, doc-surrealdb_versioned_docs/version-latest/cli/upgrade.mdx, doc-surrealdb_versioned_docs/version-latest/cli/validate.mdx, doc-surrealdb_versioned_docs/version-latest/cli/version.mdx, doc-surrealdb_versioned_docs/version-latest/installation/upgrading/beta.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/commit.mdx
This changes the beta guide to note the following:
* Manual export and import is only required when moving from 2.0.0-alpha to 2.0.0-beta
* Otherwise, use the surreal fix command.
Also adds a page to the CLI commands for the surreal fix command.
In addition, the order has been changed a little which I think makes sense:
* surreal start
* surreal sql
* surreal help
* All the rest in alphabetical order
=> Change beta guide, add fix command to CLI

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/time.mdx
The documentation for the `time::month()` function uses the `time::minute()` function in the API definition. This commit corrects this to use the `time::month()` function.
=> docs-Fix typo in `time::month()` function documentation

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/session.mdx
The documentation page for the Session functions currently has the description from the documentation page for the String functions:
"These functions can be used when working with and manipulating text and string values."
This commit replaces this with the following description:
"These functions return information about the current SurrealDB session."
The documentation page for the Session functions include:
"The `session::ac` function replaces the `session::sc` function and returns the current user's access method."
This commit changes this to keep the description of the function in its own sentence, and mention the change in a separate note. This is consistent with how other parts of the documentation flag when a new version of SuurealDB has changed a function name, such as …
=> docs-Changes to the Session functions documentation page

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/record.mdx
On the documentation page for the Record functions, the title is omitted from the page's source code, causing the page's title to default to the title from the page's header metadata ("Record functions | SurrealQL")
This commit adds the explicit page tile of "Record functions" to make the page's title format consistent with the rest of the function documentation pages ("Record functions").
=> docs-Add title to Record functions documentation page

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/parse.mdx
On the documentation page for the Parse functions, the list of functions includes the `parse::url::port()` function twice, The second appearance was intended to be the `parse::url::scheme()` function.
This commit changes the second appearance to `parse::url::scheme()`.
On the documentation page for the Parse functions, many of the functions currently show a return type of `bool` in the API definitions, instead of their correct return types.
This commit changes the return type shown in the API definitions of the following functions  to `string`:
`parse::email::user`
`parse::url::domain`
`parse::url::fragment`
`parse::url::host`
`parse::url::path`
`parse::url::scheme`
`parse::url::query`
This commit changes the return type shown in the API definitions of the following functions  to …
=> docs-Fixes to the Parse functions documentation page

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/index.mdx
On the documentation overview page for Database functions (`index.html`), the "Meta functions"  module is currently listed twice. The second appearance was intended to be the "Record functions" module.
This commit changes the second appearance of "Meta functions" to "Record functions".
=> docs-Fix typo in Database functions overview page (index.html)

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/duration.mdx
In the documentation pages for the Duration functions, the `duration::from::days` and `duration::from::weeks` functions include the wrong function name in their descriptions.
This commit corrects the function names in the descriptions.
=> docs-Fix typos in Duration functions documentation page

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/type.mdx
In the documentation page for the Type functions, the following functions' descriptions mention the wrong type which they covert values into:
`type::decimal`
`type::duration`
`type::float`
`type::int`
`type::number`
`type::string`
This commit corrects these return types.
In the documentation page for the Type functions, the description of the `type::is::record` function is missing a period at the end of the sentence.
This commit adds the missing period.
=> docs-Fix typos on Type functions documentation page 

doc-surrealdb_versioned_docs/version-latest/surrealql/datamodel/numbers.mdx
This commit adds a column to the table of mathematical constants with a description of what each constant is. These descriptions were taken from the documentation of the Rust module from which SurrealDB gets these constants (https://doc.rust-lang.org/std/f64/consts/index.html).
In the Numbers data type documentation page, the "Integer numbers" section's header is missing the header formatting ("##").
This commit adds the header formatting ("##").
This commit adds subscript formatting to the descriptions of the mathematical constants.
=> docs-Changes to Number data types documentation

doc-surrealdb_versioned_docs/version-latest/cli/start.mdx
On the documentation page for the SurrealDB CLI tool's `start` command, the description of the `path` argument says that `indxdb` can be specified to use "IndxDB" as the storage backend. The argument value is correct, but the name of the storage backend is misspelling of "IndexedDB".
This commit changes this misspelling to "IndexedDB".
In the documentation page for the CLI `surreal start` command, the usage example is the one from the `surreal version` command.
This commit replaces this with an example of how to use the `surreal start` command.
=> docs-Changes to the CLI `surreal start` command documentation

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/time.mdx
Noticed today that many of these time functions have the nice convenience of being optional, defaulting to the current datetime if no datetime argument is present.
=> Change API for many time functions which are optional

doc-surrealdb_versioned_docs/version-latest/surrealql/statements/relate.mdx
Corrected the SQL syntax in the SurrealDB documentation for inserting multiple values into the `cat` table. The original syntax used a single `INSERT INTO` statement with all values in one set, which is invalid. Updated it to use separate sets for each value, as in:
```sql
INSERT INTO cat (id) VALUES ("mr_meow"), ("mrs_meow"), ("kitten");
```
This change ensures the example executes correctly and adheres to proper SQL syntax for inserting multiple rows.
=> Fix incorrect SQL syntax for multiple INSERT values

doc-surrealdb_versioned_docs/version-latest/surrealql/functions/database/math.mdx
On the documentation page for the Math functions, the table of functions is missing the `math::tan` function.
This commit adds the missing `math::tan` function to the table.
In the Math functions documentation page, the `math::acot` function has the description of the `math::cot` function:
"Computes the cotangent of an angle given in radians"
This commit changes the description of `Math::acot` to:
"Computes the arccotangent (inverse cotangent) of an angle given in radians"
In the documentation page for the Math functions, the `math::tan` and `math::tau` appear in a different position than in the page's function table (alphabetical order).
This commit moves the `math::tan` and `math::tau` functions to the positions shown in the page's function table (alphabetical order).
In the SurrealQL …
=> docs-Changes to Math functions documentation

doc-surrealdb_versioned_docs/version-latest/integration/rpc.mdx, doc-surrealdb_versioned_docs/version-latest/surrealql/statements/define/access/record.mdx
- The clause ordering in one of the `AUTHENTICATE` examples was incorrect.
- The `SIGNIN` clause is incorrectly referred to as `SIGNUP`.
=> Fix small errors from the documentation

doc-surrealql_versioned_docs/version-latest/functions/database/count.mdx, doc-surrealql_versioned_docs/version-latest/functions/database/index.mdx, doc-surrealql_versioned_docs/version-latest/functions/database/record.mdx, doc-surrealql_versioned_docs/version-latest/functions/database/sleep.mdx, doc-surrealql_versioned_docs/version-latest/functions/database/value.mdx
This pull request adds description of each SurrealQL function module to the "Database Functions" page In the SurrealQL functions documentation.  (https://surrealdb.com/docs/surrealdb/surrealql/functions/database), as discussed in #819.
Notes for Review:
1. For each module, I used the description that is found on the dedicated page of the function module, with the following exceptions:
* For the `encoding`, `type`, and `vector` modules, the description on the dedicated page is multiple sentences, so I used only the first sentence for concision.
* The `value` module does not have a description on the dedicated page, and I am not sure what to add as one. Please advise.
2. Let me know if you think the table looks too cluttered with three columns and if it would be better to remove the …
=> docs-On Database Functions table, add column with descriptions of SurrealQL function modules

doc-surrealql_versioned_docs/version-latest/datamodel/strings.mdx
On the documentation page for the `string` data type, the following sentence is missing the word "a":
"Here is an example of record ID literal value"
This commit adds the missing word "a":
"Here is an example of a record ID literal value"
On the documentation page for the `string` data type, the example query demonstrating datetime literal values with the `d` prefix is missing the query response.
This commit adds the missing query response.
=> docs-Small fixes to `string` data type documentation

doc-surrealql_versioned_docs/version-latest/functions/database/array.mdx
In the documentation page for the `array` function module, the descriptions of the following functions are missing the word "function":
`array::boolean_and`
`array::boolean_or`
`array::boolean_xor`
`array::boolean_not`
`array::difference`
`array::find`
`array::filter_index`
`array::find_index`
`array::flatten`
`array::is_empty`
`array::logical_and`
`array::logical_or`
`array::logical_xor`
`array::max`
`array::matches`
`array::min`
`array::swap`
`array::transpose`
This commit adds the missing word "function" to the descriptions.
In the documentation page for the `array` function module, the API definition appears above the function description for the following functions:
`array::all`
`array::find`
`array::find_index`
This commit moves the API definitions of these functions below the …
=> docs-Changes to `array` function module documentation

src/content/doc-surrealql/statements/define/analyzer.mdx
This PR changes the DEFINE ANALYZER page to move from a preparatory "for example, the output will be..." to having each example use the `search::analyze()` function to show the output instead.
Also moves the filters around a bit so that they introduce similar filters next to each other:
* Simple ones: ascii, lowercase, uppercase
* -gram ones: ngram, edgengram
* Snowball
=> Add search::analyze output to DEFINE ANALYZER

src/content/doc-sdk-php/setup.mdx
This PR fixes the installation command in the PHP docs, as `composer add` doesn't exist.
The command in the PHP package README is correct, so that one is used for consistency.
=> docs: correction to installation with Composer

src/content/doc-sdk-javascript/core/index.mdx, src/content/doc-sdk-javascript/core/streaming.mdx
Javascript 1.0 package does not have a listenLive function. Instead, there exists a new version using subscribeLive
=> fix: rename listenLive to subscribeLive

src/content/doc-surrealdb/deployment/fly.mdx
as [PATH] argument prefix"file://" of the command 'surreal start' is deprecated, CMD property of the fly.io deployment Dockerfile should have "surrealkv://" or "rocksdb://" as [PATH] prefix for the start command. source : https://surrealdb.com/docs/surrealdb/cli/start
=> fly deployment - Add warning for file:// 

src/content/doc-surrealql/datamodel/ids.mdx
Not sure why the `# Learn More` section was added with the blog post, I guess I had an older fork, but I think it's worthwhile keeping that link there
=> Document algorithm for `record:rand()` generations

src/content/doc-surrealql/datamodel/numbers.mdx, src/content/doc-surrealql/functions/database/math.mdx
Closes #832.
The documentation page for the numeric data types is missing the following two constants:
`math::inf`
`math::neg_inf`
This commit adds the two missing constants.
The documentation page for the math` function module is missing the following constants:
`math::frac_1_pi`
`math::frac_1_sqrt_2`
`math::frac_2_pi`
`math::frac_2_sqrt_pi`
`math::frac_pi_2`
`math::frac_pi_3`
`math::frac_pi_4`
`math::frac_pi_6`
`math::frac_pi_8`
`math::ln_10`
`math::ln_2`
`math::log10_2`
`math::log10_e`
`math::log2_10`
`math::log2_e`
`math::sqrt_2`
This commit adds the missing constants.
=> docs-Add missing `math` constants to documentation pages of numeric data types and `math` function module

src/content/doc-surrealql/statements/insert.mdx
Saw that we say in the syntax that `relation` comes after `into` but it actually comes before, like the examples below show.
=> Correct the syntax

src/content/doc-surrealdb/embedding/rust.mdx
Added an example of how to use RocksDB embedded.
Example was added in comments to make sure the code snippet would still run if just copy and pasted.
=> Add rocksdb example to embed doc

src/content/doc-surrealql/statements/update.mdx, src/content/doc-surrealql/statements/upsert.mdx
Small PR: our SDK update and upsert functions are often (always?) divided into three depending on which clause to use and users will benefit from seeing them in the menu on the right.
=> Add CONTENT/PATCH headers to upsert and update

src/content/doc-surrealql/statements/create.mdx, src/content/doc-surrealql/statements/relate.mdx, src/content/doc-surrealql/statements/select.mdx
This clarifies that PARALLEL still carries the same transaction guarantees as any other statement, along with "concurrently, rather than sequentially" and similar phrasings to explain what "parallel" refers to.
=> Clarify PARALLEL keyword

src/content/doc-surrealql/datamodel/ranges.mdx
This commit updates the documentation page for the SurrealQL range type to add semicolons to the end of all statements for consistency, and so that the examples will be valid if pasted into Surrealist and run.
This commit also changes the formatting of the examples of type casting a range into an array to add a space in between the type and the value being cast, to be consistent with the formatting of type casting in the rest of the documentation.
=> Tweak formatting on SurrealQL ranges documentation

src/content/doc-surrealql/statements/show.mdx
The SHOW page demonstrates that it can take a versionstamp in addition to a timestamp, but the syntax doesn't show this yet.
=> Syntax fix: SHOW can take a versionstamp

src/components/Sidebar/RenderSidebarLink.astro, src/util/doc.ts
There was an issue where the segments of an url were inproperly matched. So for example you selected a link that leads you to `insert` and there was another entry called `insert-relation`. both the links were highlighted instead of `insert`. This pull request resolves that issue.
=> Fix: url segments matching

src/content/doc-surrealql/statements/create.mdx
Comment described creation of `numeric` ID, but it is a `text` ID.
[Reported via Discord](https://discord.com/channels/902568124350599239/1181598754122518642/1306114646498869289)
=> Fix comment describing Record ID creation

src/content/doc-surrealql/statements/define/param.mdx
Closes https://github.com/surrealdb/docs.surrealdb.com/issues/971 by noting that DEFINE PARAM can take a PERMISSIONS clause.
=> DEFINE PARAM can take a PERMISSIONS clause

src/content/doc-surrealql/datamodel/ranges.mdx, src/content/doc-surrealql/statements/select.mdx
Closes https://github.com/surrealdb/docs.surrealdb.com/issues/949
Also notes that there is an improvement to both readability and performance if a range is used to replace a wordy check like `WHERE age >= 18 AND age <= 65`.
For the `SELECT` page, the numeric example is a nice way to get the reader into range-reading mode before the more complex record range examples start.
=> Add info on ranges in WHERE clause

src/content/doc-surrealql/statements/define/event.mdx
Some users have asked about this before, and [the source code](https://github.com/surrealdb/surrealdb/blob/a5c3637957e91afe267ac41f2cd50bde35363cf8/core/src/doc/event.rs#L10) has the answer:
```
/// Processes any DEFINE EVENT clauses which
/// have been defined for the table which this
/// record belongs to. This functions loops
/// through the events and processes them all
/// within the currently running transaction.
```
A few words inside the top-level note seem to be enough to make it clear.
=> Note that events are run within the current transaction

src/content/doc-surrealql/datamodel/futures.mdx, src/content/doc-surrealql/statements/define/field.mdx
Closes https://github.com/surrealdb/docs.surrealdb.com/issues/183, addresses one item in https://github.com/surrealdb/docs.surrealdb.com/issues/559
This PR mentions that futures can be included in schema definitions, but also rewrites the DEFINE FIELD page a bit in three other ways:
1) General improvements like removing old syntax
2) Rearranging sections for a bit more unified narrative
3) Mentions that VALUE is recalculated every time an update happens (users have mentioned wanting to see this on Discord before, though no official issue has been created) and then uses that as the launching point to mention how futures inside a schema work.
=> Define field and future improvements

src/content/doc-surrealdb/deployment/kubernetes.mdx
migration to 2.0: use new helm chart template value to allow unauthorised access because of change in env vars.
This change depends on: https://github.com/surrealdb/helm-charts/pull/9  -- where new template value surrealdb.unauthorised is introduced.
=> migration to 2.0: use new helm chart template value to allow unauthorised access

src/content/doc-surrealql/statements/define/field.mdx, src/content/doc-surrealql/statements/define/table.mdx, src/content/doc-surrealql/statements/relate.mdx
The `$this` parameter isn't needed inside a `DEFINE FIELD` statement to refer to individual fields of the parent record (so removes those), but adds an example to show that it can be useful in cases like using a future that relies on the whole record.
=> Rewrite $this parameter usage in DEFINE FIELD

src/content/doc-sdk-rust/methods/export.mdx
Documentation for the newly merged export config in the Rust SDK: https://github.com/surrealdb/surrealdb/pull/5125
=> Rust SDK: add export config options

src/content/doc-surrealql/datamodel/idioms.mdx
The idioms.mdx page contains an incorrect output for an example query.
I would also suggest clarifying the usage of the idiom `.*` and instead using `*`. For instance, in this section, it’s referring to the dot notation but doesn’t use it in the queries.
``````mdx
The `.*` idiom can also be used in queries to select all properties of an object or record.
```surql
CREATE ONLY person:tobie SET name = 'tobie';
SELECT * FROM ONLY person:tobie;
```
**Result:**
```surql
{
"id": "person:tobie",
"name": "tobie"
}
```
``````
=> fix: update idioms.mdx

src/content/doc-sdk-golang/start.mdx
The Delete method returns 2 arguments: an ID and a result. This PR adds ignoring the first one. Without this change it won't compile.
The Go SDL used is `github.com/surrealdb/surrealdb.go v0.3.0` in go.mod.
=> Fix the example script

src/content/doc-surrealql/datamodel/idioms.mdx, src/content/doc-surrealql/statements/relate.mdx
Does the following:
* Full proofreading and rewrite of RELATE to make it easier to follow and in order of increasing difficulty,
* Adds some examples to RELATE of recursive paths,
* Notes inside the idioms page that the recursive syntax is also useful for filtering the very queries that generate them.
Notes on the RELATE rewrite:
* Starts with named instead of random record IDs (e.g. person:aristotle) to make it more obvious that the 'wrote' table will get a random ID by default (and to make it easier to read the output)
* Restructures the menu on the right so that the page is clearly divided into two sections: 1 the statement, 2 graph querying. The #### levels disappear from the menu but looks cleaner in this way IMO
* Adds more output examples and examples that span multiple queries
* …
=> Rewrite RELATE, add examples of filtering recursive queries

src/content/doc-surrealql/statements/define/event.mdx
Resolves https://github.com/surrealdb/docs.surrealdb.com/issues/1021 in which @welpie21 kindly points out that the event is drawing from $this (the event) is accessing the log being created, instead of the user (which is located at $value). Also makes the example a little more fun + ensures that before_email and after_email are always present in the log. These may have the value NONE, in which case their field won't show up at all, and a log would probably rather see something like a '' empty string to show a lack of email.
https://github.com/surrealdb/docs.surrealdb.com/compare/fix-define-event-example?expand=1
=> Fix DEFINE EVENT example

src/content/doc-sdk-rust/setup.mdx
Adds a recommendation for Rust SDK users building in release mode to use the same release profile that SurrealDB itself does.
=> Recommend profile.relase for Rust SDK

src/content/doc-surrealql/datamodel/idioms.mdx
The `.@` repeat recurse symbol could use some more explanation. Also adds the unfolded example that Micha provided.
=> Explain repeat recurse better

src/content/doc-surrealql/statements/create.mdx, src/content/doc-surrealql/statements/insert.mdx, src/content/doc-surrealql/statements/relate.mdx, src/content/doc-surrealql/statements/update.mdx, src/content/doc-surrealql/statements/upsert.mdx
It is possible in certain `RETURN` statements to utilize the `VALUE` clause.
[Surrealist Example](https://surrealist.app/mini?query=--+Returns+object+as+default%0AUPSERT+ONLY+sequence%3Atask1+SET+%60value%60+%2B%3D+1%3B%0A%0A--+Returns+%60value%60+using+idioms%0A%28UPSERT+ONLY+sequence%3Atask1+SET+%60value%60+%2B%3D+1%29.%60value%60%3B%0A%0A--+Returns+object+of+%60value%60+using+RETURN+statement%0AUPSERT+ONLY+sequence%3Atask1+SET+%60value%60+%2B%3D+1+RETURN+%60value%60%3B%0A%0A--+Returns+%60VALUE%60+using+RETURN+statement+%28undocumented%29%0AUPSERT+ONLY+sequence%3Atask1+SET+%60value%60+%2B%3D+1+RETURN+VALUE+%60value%60%3B&orientation=horizontal&nonumbers=true)
```surql
-- Returns object as default
UPSERT ONLY sequence:task1 SET `value` += 1;
-- Returns `value` using idioms
(UPSERT ONLY …
```
=> refactor: Add optional VALUE statements

src/content/doc-surrealdb/cli/start.mdx
PR to try to make it clear that surreal start doesn't take namespace or database arguments and that surreal sql is the place for that.
=> Surreal start has nothing to do with namespace/database

src/content/doc-cloud/faqs/index.mdx
Adds GraphQL as one of the features not yet enabled for Surreal Cloud.
=> GraphQL not yet available for Cloud

src/content/doc-surrealql/datamodel/ids.mdx
Small clarification that :rand() is called by default so that the reader knows that `CREATE temperature` and `CREATE temperature:rand()` are identical.
=> Clarify that :rand() is the default

src/content/doc-surrealdb/embedding/javascript.mdx
The location of these documentation pages have changed,
Current: https://surrealdb.com/docs/sdk/javascript/engines/nodejs
Updated: https://surrealdb.com/docs/sdk/javascript/engines/node
=> Update outdated links

src/content/doc-surrealql/statements/info.mdx
Add a note that INFO currently can only be used on its own, not as a parameter or in other queries.
=> Note that INFO currently can only be used on its own

src/content/doc-surrealql/statements/relate.mdx
Closes https://github.com/surrealdb/docs.surrealdb.com/issues/973 with an example showing how parentheses can be used at each step of a graph query (plus destructuring at the end)
=> Add extra example of parentheses in graph queries

src/content/doc-surrealql/datamodel/idioms.mdx
Makes .* more prominent since users gravitate towards that operator first.
=> Make .* more prominent than [*]

src/content/doc-tutorials/using-github-actions.mdx
Our GitHub Action docs are referencing the old version of `surrealdb/setup-surreal`.
https://surrealdb.com/docs/tutorials/using-github-actions
These changes update for the current usage recommendations of version 2.
https://github.com/surrealdb/setup-surreal?tab=readme-ov-file#usage
=> Update GitHub Actions documentation

src/content/doc-surrealql/transactions.mdx
Adds an example of how a transaction can be used for simple testing.
=> Example of how transactions can be used for tests

src/content/doc-surrealql/statements/relate.mdx
Adds an example of where it might make sense to use RELATE before the records themselves exist.
=> Add example of graph edges existing before records exist

src/content/doc-surrealql/statements/define/table.mdx
Ensure that casual readers know that the fields of a table are defined in a separate statement.
=> Add note that fields are defined inside DEFINE FIELD, not DEFINE TABLE

src/content/doc-surrealql/functions/database/array.mdx
Explains array::fold and array::reduce a bit better.
=> Better wording for array::reduce and fold

src/content/doc-surrealql/functions/database/meta.mdx, src/content/doc-surrealql/functions/database/record.mdx
The warnings on the top of the record functions page should be replaced with a single note that just mentions that they used to be inside the meta:: module.
=> Change warning to note for record functions

src/content/doc-surrealql/functions/database/type.mdx
Adds an example showing how type::thing can be used to turn an array of objects into records.
=> Add example of type::thing to turn array of objects into records

src/content/doc-sdk-rust/index.mdx
Somehow the word JDK slipped in here. 1.80.1 refers to the minimum Rust version. Resolves https://github.com/surrealdb/docs.surrealdb.com/issues/1075
=> rv JDK typo

src/content/doc-surrealdb/security/summary.mdx
This pull request fixes a minor typo in the documentation. The word "later" was incorrectly used and has been corrected to "latter" to accurately reflect the intended meaning.
**Changes Made**
Corrected "later" to "latter" in the relevant documentation section.
**Rationale**
Using "latter" aligns with the intended meaning and improves the clarity and accuracy of the documentation.
=> docs: fix typo in documentation (later -> latter)

src/content/doc-surrealql/functions/database/array.mdx, src/content/doc-surrealql/functions/database/math.mdx, src/content/doc-surrealql/functions/database/time.mdx
Users on one of the ::min or ::max methods may be interested in knowing that there is a similar function for other types. e.g. that you can use time::max for datetimes.
=> Add some see also for each of the min and max methods

src/content/doc-sdk-rust/methods/new.mdx, src/content/doc-surrealdb/cli/start.mdx, src/content/doc-surrealql/statements/create.mdx, src/content/doc-surrealql/statements/select.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/5163 which since 2.1.1 has made non-versioning the default for SurrealKV.
=> SurrealKV versioning now disabled by default

src/content/doc-surrealql/statements/define/field.mdx
Adds another example inside DEFINE FIELD that includes specifying the maximum number of items in an array.
=> Add example of max number of items in an array

src/content/doc-surrealql/parameters.mdx, src/content/doc-surrealql/statements/delete.mdx
Two small changes:
1) Makes it clear in the parameters page that $event can be one of three values. This is already present in another page but best to make it available here too.
2) Finishes an incomplete sentence in the soft deletion section of the DELETE page which somehow got through unnoticed.
=> Small event improvements

src/content/doc-surrealql/statements/info.mdx
Relates to https://github.com/surrealdb/surrealdb/pull/5227 and  https://github.com/surrealdb/surrealdb/pull/5238
Here is the addition:
https://deploy-preview-1054--surrealdb-docs.netlify.app/docs/surrealql/statements/info/#root-information
=> Documents info for root system information

src/content/doc-surrealql/datamodel/ids.mdx
Shows that record IDs inside a schema are of type `record`.
=> Show what type records are inside a schema

src/content/doc-surrealql/functions/database/object.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/5303
Resolves https://github.com/surrealdb/docs.surrealdb.com/issues/1087
=> Document object::is_empty()

src/components/RenderDoc.astro
Code blocks were rendering on top of the navigation menu on mobile devices
=> Fix navigation menu on mobile devices

src/content/doc-surrealdb/cli/env.mdx
The env var SURREAL_WEBSOCKET_MAX_CONCURRENT_REQUESTS has changed its default value: https://github.com/surrealdb/surrealdb/pull/5384
=> New default for SURREAL_WEBSOCKET_MAX_CONCURRENT_REQUESTS

src/content/doc-cloud/faqs/index.mdx
Fixing small typos in the security FAQs
=> Docs: fix typos in FAQ

src/content/doc-surrealql/functions/database/array.mdx
Corrects the signature of array::transpose and adds a few examples.
=> Improve array::transpose + add examples

src/content/doc-surrealql/functions/database/array.mdx
Documents this improvement to array::transpose, which is a breaking change: https://github.com/surrealdb/surrealdb/pull/5433
=> New array::transpose behaviour

src/content/doc-surrealql/statements/select.mdx
Clarifies that if you choose VALUE in SELECT, you only get to choose one field and that's the end of it.
=> Clarify that VALUE means a single field

src/content/doc-surrealql/functions/database/sleep.mdx, src/content/doc-surrealql/statements/define/indexes.mdx, src/content/doc-surrealql/statements/info.mdx
Improves concurrent indexing documentation.
Document the modifications done on INFO FOR INDEX on v2.2
The PR for SurrealDB:
https://github.com/surrealdb/surrealdb/pull/5482
The updated pages:
https://deploy-preview-1158--surrealdb-docs.netlify.app/docs/surrealql/statements/info/#index-information
https://deploy-preview-1158--surrealdb-docs.netlify.app/docs/surrealql/statements/define/indexes/#using-concurrently-clause
https://deploy-preview-1158--surrealdb-docs.netlify.app/docs/surrealql/functions/database/sleep/#sleep-during-parallel-operations
=> Documents INFO FOR INDEX + concurrent indexing

src/components/Search.astro, src/components/Sidebar/index.astro, src/components/layout/BaseLayout.astro
- Able to show the searchbar on smaller devices. It would be displayed in the sidebar under the dropdown menu.
- Small fix where you could scroll entire page when sidebar was opened.
=> DOC-343: show search bar mobile

src/content/doc-surrealql/statements/define/table.mdx
In the SurrealQL documentation page for the DEFINE TABLE statement, one of the query examples has a literal date value created using `u"2023-09-07T01:23:52Z"`, which is the syntax for a literal UUID value.
This commit changes this to `d"2023-09-07T01:23:52Z"`, using the syntax for a literal date value.
=> Fix query syntax in SurrealQL DEFINE TABLE statement page

src/content/doc-surrealdb/installation/windows.mdx
Running the install command doesn't work to update, but `surreal update` does, so updating that in the docs.
=> Update windows update

src/content/doc-surrealdb/deployment/amazon.mdx, src/content/doc-surrealdb/deployment/azure.mdx, src/content/doc-surrealdb/deployment/fly.mdx, src/content/doc-surrealdb/deployment/google.mdx, src/content/doc-surrealdb/deployment/kubernetes.mdx, src/content/doc-surrealdb/faqs/index.mdx, src/content/doc-surrealdb/introduction/architecture.mdx, src/content/doc-surrealdb/reference-guide/vector-search.mdx
- Fixed typos in “underlying”, “create”, “cluster”, and “minimum”
- More consistent spelling of “TiKV” (with the lowercase “i”)
- More consistent spelling of “analyzer” (US English spelling prevails throughout the rest of the docs)
- More consistent spelling of “URL” in deployment docs
- Changed IAM policy document path to `file://`
- Some punctuation and whitespace fixes
- Tried to reconstruct the missing text in “How do I scale SurrealDB?” FAQ section about FoundationDB
=> Fix typos in SurrealDB Docs

src/content/doc-surrealql/statements/define/field.mdx
Since ASSERT expects a bool, users can manually implement it too by returning true in certain cases and using THROW to return a custom message too.
=> Add example of custom message for ASSERT

src/content/doc-surrealql/functions/database/record.mdx
On the documentation page for the SurrealQL record function module, the function `record::refs()` is listed with the description and hyperlink of the `record::tb()` function.
This commit updates the `record::refs()` function with the correct definition and hyperlink.
=> Fix SurrealQL `record::refs()` function typos

src/content/doc-surrealql/functions/database/string.mdx
If you want to join an array of strings, it can be confusing where to go, so added link to `array::join` to the `string::join` docs.
=> Improve string join docs

src/content/doc-surrealql/clauses/order_by.mdx, src/content/doc-surrealql/functions/database/array.mdx, src/content/doc-surrealql/statements/select.mdx
Documentation for https://github.com/surrealdb/surrealdb/pull/5585
Also includes some changes to the syntax in both the SELECT and CLAUSE page. This seems to be the gist of it:
* Order by, then possibly COLLATE and/or NUMERIC, then ASC/DESC, then repeat with any other fields...
* Or just rand() and call it a day
=> Array sort natural lexical

src/content/doc-surrealql/parameters.mdx
Adds a bit of info to the parameters page to show exactly which four variables can never be set by a user.
=> Mention which four variables are specifically protected

src/content/doc-surrealql/functions/database/type.mdx
Interesting bit about type::thing: if the second argument is a full record ID, it will extract the latter part and use that.
=> Note about type::thing when it gets a full record

src/content/doc-surrealql/parameters.mdx
Clarifies that parameters are set on the connection level, allowing them to be reused across namespaces and databases.
=> Mention that parameters are set on the connection level

src/content/doc-surrealql/statements/define/field.mdx
Add a section which explains to define the TYPE for the id field of a record.
Fixes #1241
=> Add section to define the TYPE for the id field

src/content/doc-sdk-javascript/engines/node.mdx, src/content/doc-sdk-rust/frameworks/actix.mdx, src/content/doc-sdk-rust/frameworks/axum.mdx, src/content/doc-sdk-rust/frameworks/egui.mdx, src/content/doc-sdk-rust/frameworks/rocket.mdx, src/content/doc-surrealdb/introduction/start.mdx, src/content/doc-surrealkv/index.mdx, src/content/doc-surrealkv/performance.mdx
There are currently only two pages with the info that `+versioned` is needed to start SurrealKV with versioning, so sprinkles a few more examples here and there.
=> Add a few more examples of +versioned for SurrealKV

src/content/doc-surrealql/datamodel/ids.mdx, src/content/doc-surrealql/functions/database/type.mdx
Adds some advice that array-based record IDs are most effective if any parts that are likely to be used as exact matches (like record IDs or enum-like things like "debug") are moved to the front.
Also fixes a signature or two in the functions page.
=> More record range advice

src/content/doc-surrealdb/reference-guide/performance-best-practices.mdx, src/content/doc-surrealql/datamodel/booleans.mdx
Adds a tip for when WHERE can't be avoided: try to simplify the operation as much as possible, if possible by making it a quick bool check. The same tip is included in both the performance page as well as the boolean page which is quite small at the moment.
=> Add tip on using bools to speed things up a bit

src/content/doc-surrealdb/models/time-series.mdx, src/content/doc-surrealql/datamodel/ids.mdx, src/content/doc-surrealql/datamodel/values.mdx, src/content/doc-tutorials/define-a-schema.mdx
Array-based complex IDs are better than object-based, so remove mention of the latter from the docs
=> recommend array-based record IDs

src/content/doc-surrealdb/cli/env.mdx
Adds docs for the new `SURREAL_SCRIPTING_MAX_TIME_LIMIT` environment variable introduced in surrealdb/surrealdb#5597
=> Add docs for new javascript function timeout env

src/content/doc-surrealql/functions/database/array.mdx
Adds a tip: Because the inner closure in array::filter is checked for truthiness and not just a boolean value, you can just pass on any value and if it's not truthy it will be filtered out. Especially useful in graph queries
=> Add tip for when using array::filter

src/content/doc-sdk-javascript/data-types.mdx, src/content/doc-sdk-php/data-types.mdx, src/content/doc-sdk-python/data-types.mdx, src/content/doc-surrealql/datamodel/geometries.mdx
Adds an extra warning and some links from the SDKs so users are very aware that the GeoJSON spec order is used to create  point.
=> Add warning about order of Points

src/content/doc-surrealql/statements/access.mdx
Closes https://github.com/surrealdb/surrealdb/issues/4564
Adds example of THROW used inside a DEFINE ACCESS statement and how to test the output.
=> Add example of THROW inside DEFINE ACCESS

src/content/doc-surrealql/datamodel/ids.mdx
Adds an example showing that record ranges aren't magic but just able to benefit from scanning a really small space.
=> Add section on why record ranges are performant

src/content/doc-surrealdb/reference-guide/sample-industry-schemas.mdx
- Ensure the [SCADA (Oil and Gas)](https://surrealdb.com/docs/surrealdb/reference-guide/sample-industry-schemas#scada-oil-and-gas) example’s alert only fires on a pressure drop > 15 PSI so the text (“Pressure drop over 15 PSI”) always matches the guard.
- Update the [Other bank-customer schema](https://surrealdb.com/docs/surrealdb/reference-guide/sample-industry-schemas#other-bank-customer-schema) example to use `set<string>` as the supported_currencies field type (previously `array<string>`).
=> docs: minor updates to examples in sample-industry-schemas.mdx

src/content/doc-surrealql/statements/insert.mdx
It turns out that ON DUPLICATE KEY UPDATE also applies to a unique index, which is convenient.
=> Add example of unique key for ON DUPLICATE KEY UPDATE

src/content/doc-sdk-rust/methods/query.mdx
Clarify that Ok() for .query() means the queries successfully executed, not necessarily that each one was a successful result.
=> Clarify what success for .query() means

src/content/doc-surrealql/functions/database/encoding.mdx
There was a small copy/paste error on the encoding function page. So I fixed it :)
=> Typo: Fixed typo on encoding functions

src/content/doc-surrealdb/reference-guide/index.mdx
This pull request adds two new documentation links that were listed in the sidebar but missing in the main content page
New documentation links:
* Added a link to the "Sample Industry Schemas".
* Added a link to the "Schema Best Practices".
=> Update reference guide with missing topics

src/content/doc-surrealdb/cli/start.mdx
Sometimes a user will pass in a single path by mistake (e.g. rocksdb:/path or surrealkv:/path) which is interpreted as an absolute path, then if permissions aren't high enough it ends in a cryptic message. This adds some advice in that case.
=> Add a slash hint

src/content/doc-surrealdb/integration/cbor.mdx, src/content/doc-surrealql/datamodel/formatters.mdx, src/content/doc-surrealql/datamodel/index.mdx, src/content/doc-surrealql/datamodel/strings.mdx, src/content/doc-surrealql/functions/database/string.mdx
Clarifies that SurrealDB datetimes are the RFC 3339 format.
=> Change ISO to RFC
